using ATG.Platform.Domain.Enums;

namespace ATG.Platform.Infrastructure.Seeds;

/// <summary>Bukhara Main Gas Management Center (BMGMC) org chart — bilingual RU/EN.</summary>
public static class BmgmcMasterData
{
    public const string OrganizationCode = "BMGMC";

    public static readonly HoDepartment[] Departments =
    [
        new("BMGMC-EXEC", "Руководство", "Leaders"),
        new("BMGMC-SEC", "Отдел безопасности", "Security Section"),
        new("BMGMC-HR", "Отдел кадров", "HR Section"),
        new("BMGMC-DCPR", "Отдел по делопроизводству", "Document Control Section"),
        new("BMGMC-ADM", "Административно-хозяйственный отдел", "Administrative Section"),
        new("BMGMC-ACCT", "Отдел бухгалтерского учёта и финансов", "Accounting and Finance Section"),
        new("BMGMC-TRANS", "Транспортный отдел", "Transport Section"),
        new("BMGMC-HSE", "Отдел по ТБ и ООС", "HSE Section"),
        new("BMGMC-GCC", "Центральный диспетчерский узел", "General Control Center"),
        new("BMGMC-TECH", "Отдел по техническим вопросам", "Technical Affairs Section"),
        new("BMGMC-ITDIG", "Отдел цифровизации и автоматизации", "Digitalization and Automation Section"),
        new("BMGMC-CALIB", "Поверочная лаборатория", "Calibration Laboratory"),
        new("BMGMC-RMC", "Центр ремонта и техобслуживания", "Repair and Maintenance Center"),
        new("BMGMC-PIPE", "Отдел по управлению трубопроводом", "Pipeline Management Section"),
        new("BMGMC-SUP", "Отдел снабжения", "Supply Section"),
        new("BMGMC-DORM", "Вахтовое общежитие эксплуатационного персонала", "Shift Dormitory for Operational Personnel"),
    ];

    public static readonly string[] LegacyDepartmentCodes = ["BMGMC-OPS", "BMGMC-ENG", "BMGMC-SAF", "BMGMC-IT"];

    public static readonly HoStaffMember[] Staff =
    [
        // Руководство / Leaders
        new("ATG-158", "Чжэньдун", "Хао", null, "Zhendong", "Hao", null, "haozhendong@atg.uz", "93 111 33 91", "2388, 2575", "BMGMC-EXEC",
            "Генеральный менеджер по эксплуатации — начальник Бухарского ОУМГ", "General Manager for operation — Director of Bukhara MGMC", "TOP_MANAGER", UserRole.BMGMCManager),
        new("ATG-159", "Отабек", "Комилов", "Олимович", "Otabek", "Komilov", "Olimovich", "o.komilov@atg.uz", "94 660 05 48, 97 037 80 09", "2305", "BMGMC-EXEC",
            "Первый заместитель генерального менеджера по эксплуатации — заместитель начальника Бухарского ОУМГ", "First Deputy of General Manager for operation — Deputy Director of Bukhara MGMC", "MANAGER", UserRole.BMGMCManager),
        new("ATG-160", "Рустам", "Рахматов", "Шавкатович", "Rustam", "Rakhmatov", "Shavkatovich", "r.rakhmatov@atg.uz", "94 660 30 44", "2302, 2202", "BMGMC-EXEC",
            "Заместитель начальника Бухарского ОУМГ по общим вопросам", "BMGMC Deputy Director for Administrative affairs", "MANAGER", UserRole.BMGMCManager),
        new("ATG-161", "Чэнсян", "Ван", null, "Chengxiang", "Wang", null, "wangchengxiang@atg.uz", "94 660 26 30", "2328, 2569", "BMGMC-EXEC",
            "Заместитель начальника Бухарского ОУМГ по техническим вопросам", "BMGMC Deputy Director for Technical Affairs", "MANAGER", UserRole.BMGMCManager),
        new("ATG-162", "Гомин", "Лю", null, "Guoming", "Liu", null, "liuguoming@atg.uz", "94 888 03 69", "2368", "BMGMC-EXEC",
            "Заместитель начальника Бухарского ОУМГ по диспетчеризации", "BMGMC Deputy Director for Gas Dispatching", "MANAGER", UserRole.BMGMCManager),
        new("ATG-163", "Шухрат", "Шохназаров", null, "Shukhrat", "Shokhnazarov", null, "sh.shokhnazarov@atg.uz", "94 660 56 01", "2333", "BMGMC-EXEC",
            "Помощник начальника", "Assistant Director", "SPECIALIST", UserRole.BMGMCNachalnikiOtdeli),

        // Отдел безопасности / Security Section
        new("ATG-164", "Уйгун", "Темуров", null, "Uygun", "Temurov", null, "u.temurov@atg.uz", "50 052 90 07", "2307, 2007", "BMGMC-SEC",
            "Начальник отдела безопасности", "Security section manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-165", "Дониёр", "Рахманов", null, "Doniyor", "Rakhmanov", null, "d.rakhmanov@atg.uz", "94 660 22 43", "2586, 2504", "BMGMC-SEC",
            "Специалист по безопасности", "Security officer", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-166", "Бехзод", "Сайфуллаев", null, "Bekhzod", "Sayfullaev", null, "b.sayfullaev@atg.uz", "50 155 16 63", "2587", "BMGMC-SEC",
            "Специалист по безопасности", "Security officer", "SPECIALIST", UserRole.BMGMCEngineer),

        // Отдел кадров / HR Section (vacant HR manager row skipped — no name/email)
        new("ATG-167", "Валентина", "Лавренко", null, "Valentina", "Lavrenko", null, "v.lavrenko@atg.uz", "94 660 56 10", "2325", "BMGMC-HR",
            "Старший специалист по кадровой политике", "HR Senior Specialist", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-168", "Носир", "Каримов", null, "Nosir", "Karimov", null, "n.karimov@atg.uz", "94 660 21 92", "2322", "BMGMC-HR",
            "Ведущий специалист по кадровой политике", "HR Leading Specialist", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-169", "Нодира", "Наимова", null, "Nodira", "Naimova", null, "n.naimova@atg.uz", "94 660 80 86", "2575", "BMGMC-HR",
            "Ведущий специалист по кадровой политике", "HR Leading Specialist", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-170", "Одилбек", "Рахматуллоев", null, "Odilbek", "Rakhmatulloev", null, "o.rakhmatulloev@atg.uz", "94 660 59 13", "2565", "BMGMC-HR",
            "Ведущий специалист по кадровой политике", "HR Leading Specialist", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-171", "Зарнигор", "Эгамова", null, "Zarnigor", "Egamova", null, "z.egamova@atg.uz", "94 660 75 05", "2595", "BMGMC-HR",
            "Специалист по корпоративной культуре", "Corporate Culture Specialist", "SPECIALIST", UserRole.BMGMCEngineer),

        // Отдел по делопроизводству / Document Control Section
        new("ATG-172", "Раъно", "Кадырова", null, "Rano", "Kadirova", null, "r.kadirova@atg.uz", "94 660 26 41", "2332", "BMGMC-DCPR",
            "Начальник отдела делопроизводства", "Manager of Document Control Section", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-173", "Евгений", "Рахматуллаев", null, "Evgeniy", "Rahmatullaev", null, "e.rahmatullaev@atg.uz", "94 660 21 56", "2010", "BMGMC-DCPR",
            "Переводчик (главный специалист) отдела делопроизводства", "Translator (Chief Officer) of Document Control Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-174", "Радик", "Байчиков", null, "Radik", "Baychikov", null, "r.baychikov@atg.uz", "94 660 21 41", "2017", "BMGMC-DCPR",
            "Переводчик (главный специалист) отдела делопроизводства", "Translator (Chief Officer) of Document Control Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-175", "Фарход", "Давронов", null, "Farkhod", "Davronov", null, "f.davronov@atg.uz", "94 660 30 66", "2317", "BMGMC-DCPR",
            "Переводчик (специалист) отдела делопроизводства", "Translator (specialist) of Document Control Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-176", "Мухаммад", "Хужамуродов", null, "Muhammad", "Khujamurodov", null, "m.khujamurodov@atg.uz", "50 177 13 67", "2583", "BMGMC-DCPR",
            "Переводчик (специалист) отдела делопроизводства", "Translator (specialist) of Document Control Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-177", "Спартак", "Садуллаев", null, "Spartak", "Sadullaev", null, "s.sadullaev@atg.uz", "94 660 26 24", "3011", "BMGMC-DCPR",
            "Переводчик (старший специалист) отдела делопроизводства", "Translator (Senior specialist) of Document Control Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-178", "Бахшилло", "Атаев", null, "Bakhshillo", "Ataev", null, "b.ataev@atg.uz", "94 655 95 40", "1012", "BMGMC-DCPR",
            "Переводчик (ведущий специалист) отдела делопроизводства", "Translator (Leading specialist) of Document Control Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-179", "Фируз", "Джураев", null, "Firuz", "Djurayev", null, "f.djurayev@atg.uz", "94 660 26 80", "8117", "BMGMC-DCPR",
            "Переводчик на объектах (КС2)", "Translator in facilities (WKC2)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-180", "Шерзод", "Юлдашев", null, "Sherzod", "Yuldashev", null, "s.yuldashev@atg.uz", "94 660 30 34", "3011", "BMGMC-DCPR",
            "Переводчик на объектах (КС1)", "Translator in facilities (WKC1)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-181", "Акмал", "Джураев", null, "Akmal", "Djuraev", null, "a.djuraev@atg.uz", "94 660 24 91", "3011", "BMGMC-DCPR",
            "Переводчик на объектах (КС1)", "Translator in facilities (WKC1)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-182", "Ильхом", "Холиков", null, "Ilkhom", "Kholikov", null, "i.kholikov@atg.uz", "94 660 26 72", "7010", "BMGMC-DCPR",
            "Переводчик на объектах (ГКС)", "Translator in facilities (GCS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-183", "Равшан", "Мурадов", null, "Ravshan", "Muradov", null, "r.muradov@atg.uz", "94 660 30 67", "5008", "BMGMC-DCPR",
            "Переводчик на объектах (КС3)", "Translator in facilities (WKC3)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-184", "Комил", "Рузиев", null, "Komil", "Ruziev", null, "k.ruziev@atg.uz", "94 655 02 45", "4307", "BMGMC-DCPR",
            "Переводчик на объектах (УКС3)", "Translator in facilities (UCS3)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-185", "Ихтиёр", "Саидов", null, "Ikhtiyor", "Saidov", null, "i.saidov@atg.uz", "94 660 02 42", "8117", "BMGMC-DCPR",
            "Переводчик на объектах (КС2)", "Translator in facilities (WKC2)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-186", "Шухрат", "Турсунов", null, "Shukhrat", "Tursunov", null, "sh.tursunov@atg.uz", "94 660 71 13", "5008", "BMGMC-DCPR",
            "Переводчик на объектах (КС3)", "Translator in facilities (WKC3)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-187", "Гайрат", "Джабборов", null, "Gayrat", "Djabborov", null, "GayratDjabborov@atg.uz", "94 660 63 71", "4307", "BMGMC-DCPR",
            "Переводчик на объектах (УКС3)", "Translator in facilities (UCS3)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-188", "Али", "Авезов", null, "Ali", "Avezov", null, "a.avezov@atg.uz", "94 660 21 55", "9015", "BMGMC-DCPR",
            "Переводчик на объектах (УУЗРГ)", "Translator in facilities (UKMS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-189", "Александр", "Белецкий", null, "Aleksandr", "Beletskiy", null, "a.beletskiy@atg.uz", "94 660 98 18", "1012", "BMGMC-DCPR",
            "Переводчик на объектах (УКС1)", "Translator in facilities (UCS1)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-190", "Сухроб", "Садуллаев", null, "Sukhrob", "Sadullaev", null, "su.sadullaev@atg.uz", "94 888 02 37", "7010", "BMGMC-DCPR",
            "Переводчик на объектах (УУЗРГ)", "Translator in facilities (UKMS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-191", "Гузаль", "Муталова", null, "Guzal", "Mutalova", null, "g.mutalova@atg.uz", "94 660 26 86", "2316", "BMGMC-DCPR",
            "Делопроизводитель", "Document Control Officer", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-192", "Шерзод", "Каримов", null, "Sherzod", "Karimov", null, "sher.karimov@atg.uz", "50 333 05 13", null, "BMGMC-DCPR",
            "Специалист по связям с общественностью", "Public relations specialist", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-193", "Сиянат", "Ибрагимова", null, "Siyanat", "Ibragimova", null, "s.ibragimova@atg.uz", "94 660 21 27", "2583", "BMGMC-DCPR",
            "Архивариус (старший специалист) отдела делопроизводства", "Archivist (Senior specialist) of Document Control Section", "SPECIALIST", UserRole.BMGMCEngineer),

        // Административно-хозяйственный отдел / Administrative Section
        new("ATG-194", "Комилжон", "Нафетдинов", null, "Komiljon", "Nafetdinov", null, "k.nafetdinov@atg.uz", "94 660 26 98", "2320", "BMGMC-ADM",
            "Начальник административно-хозяйственного отдела", "Administrative Section Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-195", "Цюань", "Сы", null, "Quan", "Si", null, "siquan@atg.uz", "94 660 65 25", "2313, 2564", "BMGMC-ADM",
            "Заместитель начальника административно-хозяйственного отдела", "Administrative Section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-196", "Рустам", "Насруллоев", null, "Rustam", "Nasrulloev", null, "r.nasrulloev@atg.uz", "94 655 24 75", null, "BMGMC-ADM",
            "Инженер по строительству", "Construction engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-197", "Ёркин", "Абдукаримов", null, "Yorkin", "Abdukarimov", null, "yo.abdukarimov@atg.uz", "94 888 22 34", null, "BMGMC-ADM",
            "Инженер по строительству", "Construction engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-198", "Ферузжон", "Сабиров", null, "Feruzjon", "Sabirov", null, "f.sabirov@atg.uz", "98 180 00 11", "2584, 2888", "BMGMC-ADM",
            "Специалист по организационным вопросам", "Organizational Issues Officer", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-199", "Шавкат", "Гайбуллаев", null, "Shavkat", "Gaybullaev", null, "sh.gaybullaev@atg.uz", "94 660 22 32", "2340", "BMGMC-ADM",
            "Заведующий хозяйственной частью", "Household coordinator", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-200", "Ботир", "Саломов", null, "Botir", "Salomov", null, "b.salomov@atg.uz", "94 660 23 11", "2040", "BMGMC-ADM",
            "Заведующий хозяйственной частью", "Household coordinator", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-201", "Умиджон", "Ахмедов", null, "Umidjon", "Axmedov", null, "u.axmedov@atg.uz", "94 660 26 09", "8015", "BMGMC-ADM",
            "Заведующий хозяйственной частью на объекте (КС2/ГКС)", "Household coordinator in facilities (WKC2/GCS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-202", "Бахтжан", "Ирисбеков", null, "Bakhtjan", "Irisbekov", null, "b.irisbekov@atg.uz", "94 660 20 80", "5555, 5212", "BMGMC-ADM",
            "Заведующий хозяйственной частью на объекте (КС3)", "Household coordinator in facilities (WKC3)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-203", "Шамшод", "Латипов", null, "Shamshod", "Latipov", null, "sh.latipov@atg.uz", "94 744 18 55", "4440", "BMGMC-ADM",
            "Заведующий хозяйственной частью на объекте (УКС3)", "Household coordinator in facilities (UCS3)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-204", "Абдушукур", "Собиржонов", null, "Abdushukur", "Sobirjonov", null, "a.sobirjonov@atg.uz", "94 660 22 21", "6112", "BMGMC-ADM",
            "Заведующий хозяйственной частью на объекте (МС)", "Household coordinator in facilities (MS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-205", "Мирали", "Хамданов", null, "Mirali", "Khamdamov", null, "m.khamdamov@atg.uz", "94 660 69 79", "9090", "BMGMC-ADM",
            "Заведующий хозяйственной частью на объекте (УУЗРГ)", "Household coordinator in facilities (UKMS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-206", "Дурбек", "Хамидов", null, "Durbek", "Khamidov", null, "dur.khamidov@atg.uz", "94 744 22 89", "1007, 1717", "BMGMC-ADM",
            "Заведующий хозяйственной частью на объекте (КС1/УКС1)", "Household coordinator in facilities (WKC1/UCS1)", "SPECIALIST", UserRole.BMGMCEngineer),

        // Отдел бухгалтерского учёта и финансов / Accounting and Finance Section
        new("ATG-207", "Бахтийор", "Истамов", null, "Bakhtiyor", "Istamov", null, "b.istamov@atg.uz", "94 660 26 50", "2330", "BMGMC-ACCT",
            "Начальник отдела бухгалтерского учёта и финансов", "Accounting and Finance Section Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-208", "Нодир", "Курбонов", null, "Nodir", "Kurbonov", null, "n.kurbonov@atg.uz", "94 660 01 21", "2369", "BMGMC-ACCT",
            "Бухгалтер отдела бухгалтерского учёта и финансов", "Accountant of Accounting and Finance Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-209", "Шерзод", "Кошев", null, "Sherzod", "Koshev", null, "sh.koshev@atg.uz", "94 660 02 82", "2399", "BMGMC-ACCT",
            "Бухгалтер отдела бухгалтерского учёта и финансов", "Accountant of Accounting and Finance Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-210", "Ахадхон", "Мухамеджанов", null, "Akhadkhon", "Mukhamedjanov", null, "a.mukhamedjanov@atg.uz", "94 660 26 61", "2350", "BMGMC-ACCT",
            "Бухгалтер по заработной плате отдела бухгалтерского учёта и финансов", "Salary Accountant of Accounting and Finance Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-211", "Бурхон", "Муродов", null, "Burkhon", "Murodov", null, "b.murodov@atg.uz", "50 177 65 69", "2381", "BMGMC-ACCT",
            "Бухгалтер-кассир отдела бухгалтерского учёта и финансов", "Accountant-cashier of Accounting and Finance Section", "SPECIALIST", UserRole.BMGMCEngineer),

        // Транспортный отдел / Transport Section
        new("ATG-212", "Фэн", "Гао", null, "Feng", "Gao", null, "gaofeng@atg.uz", "94 660 81 71", "2023, 2561", "BMGMC-TRANS",
            "Заместитель начальника транспортного отдела", "Traffic Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-213", "Искандар", "Якубов", null, "Iskandar", "Yakubov", null, "i.yakubov@atg.uz", "94 660 24 08", "2010", "BMGMC-TRANS",
            "Начальник транспортного отдела (инженер-механик)", "Traffic Manager (Engineer-mechanic)", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-214", "Шокир", "Каримов", null, "Shokir", "Karimov", null, "sh.karimov@atg.uz", "94 660 02 32", "2525", "BMGMC-TRANS",
            "Диспетчер транспортного отдела", "Dispatcher of Transport Section", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-215", "Нозимжон", "Хайдаров", null, "Nozimjon", "Khaydarov", null, "no.khaydarov@atg.uz", "94 660 24 18", "2123", "BMGMC-TRANS",
            "Специалист по ГСМ", "POL Specialist", "SPECIALIST", UserRole.BMGMCEngineer),

        // Отдел по ТБ и ООС / HSE Section
        new("ATG-216", "Асрор", "Жураев", null, "Asror", "Juraev", null, "a.juraev@atg.uz", "94 660 26 46", "2357", "BMGMC-HSE",
            "Начальник отдела по ТБ и ООС", "HSE Section Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-217", "Цюшэн", "Дуань", null, "Qiusheng", "Duan", null, "duanqiusheng@atg.uz", "93 183 17 24", "2596, 2547", "BMGMC-HSE",
            "Заместитель начальника отдела по ТБ и ООС", "HSE Section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-218", "Нодир", "Абдуллаев", null, "Nodir", "Abdullaev", null, "n.abdullayev@atg.uz", "93 111 25 60", "2022", "BMGMC-HSE",
            "Инженер по ТБ (ОБКК)", "HSE Engineer (OBCC)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-219", "Иззатулло", "Хасанов", null, "Izzatullo", "Khasanov", null, "i.khasanov@atg.uz", "94 660 30 12", "8006", "BMGMC-HSE",
            "Инженер по ТБ (КС2, ГКС)", "HSE Engineer (WKC2, GCS)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-220", "Сухроб", "Хамраев", null, "Sukhrob", "Khamraev", null, "s.khamraev@atg.uz", "94 660 39 49", "4017", "BMGMC-HSE",
            "Инженер по ТБ (УКС3)", "HSE Engineer (UCS3)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-221", "Джалол", "Хамидов", null, "Jalal", "Khamidov", null, "d.khamidov@atg.uz", "94 660 80 70", "5114", "BMGMC-HSE",
            "Инженер по ТБ (КС3)", "HSE Engineer (WKC3)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-222", "Илхом", "Султонов", null, "Ilkhom", "Sultonov", null, "i.sultonov@atg.uz", "94 620 56 50", "5114", "BMGMC-HSE",
            "Инженер по ТБ (КС3)", "HSE Engineer (WKC3)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-223", "Руслан", "Кенжаев", null, "Ruslan", "Kenjaev", null, "r.kenjayev@atg.uz", "93 111 25 51", "3031", "BMGMC-HSE",
            "Инженер по ТБ (КС1, УКС1)", "HSE Engineer (WKC1, UCS1)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-224", "Хамдам", "Рахманов", null, "Khamdam", "Rakhmanov", null, "kh.rakhmanov@atg.uz", "50 333 05 28", "8006", "BMGMC-HSE",
            "Инженер по ТБ (КС2, ГКС)", "HSE Engineer (WKC2, GCS)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-225", "Феруз", "Жумамуродов", null, "Feruz", "Jumamurodov", null, "f.jumamurodov@atg.uz", "94 660 98 39", "9009", "BMGMC-HSE",
            "Инженер по ТБ (МС, УУЗРГ)", "HSE Engineer (MS, UKMS)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-226", "Бекмурат", "Бекбосынов", null, "Bekmurat", "Bekbosinov", null, "b.bekbosinov@atg.uz", "93 111 25 38", "9009", "BMGMC-HSE",
            "Инженер по ТБ (МС, УУЗРГ)", "HSE Engineer (MS, UKMS)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-227", "Фаррух", "Очилов", null, "Farrukh", "Ochilov", null, "f.ochilov@atg.uz", "94 660 91 71", "3031", "BMGMC-HSE",
            "Инженер по ТБ (КС1/УКС1)", "HSE Engineer (WKC1/UCS1)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-228", "Данил", "Дулатов", null, "Danil", "Dulatov", null, "d.dulatov@atg.uz", "50 787 74 48", "4017", "BMGMC-HSE",
            "Инженер по ТБ и ООС на объектах (УКС3)", "HSE engineer in facilities (UCS3)", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-229", "Сардор", "Зайниев", null, "Sardor", "Zayniyev", null, "s.zayniyev@atg.uz", "50 122 06 32", "2597", "BMGMC-HSE",
            "Инженер по промышленной безопасности", "Industrial Safety engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-230", "Светлана", "Диникеева", null, "Svetlana", "Denikeeva", null, "s.dinikeeva@atg.uz", "94 660 22 47", "2318", "BMGMC-HSE",
            "Инженер по охране окружающей среды", "Environment protection Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-231", "Анвар", "Восиев", null, "Anvar", "Vosiev", null, "a.vosiev@atg.uz", "94 660 05 75", "2337", "BMGMC-HSE",
            "Специалист по гражданской защите", "Civil Protection specialist", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-232", "Анвар", "Кадиров", null, "Anvar", "Kadirov", null, "a.kadirov@atg.uz", "94 660 84 85", "2110", "BMGMC-HSE",
            "Инженер БДД", "Traffic Safety Engineer", "ENGINEER", UserRole.BMGMCEngineer),

        // Центральный диспетчерский узел / General Control Center
        new("ATG-233", "Вэньбинь", "Ван", null, "Wenbin", "Wang", null, "wangwenbin@atg.uz", "94 660 71 03", "2578", "BMGMC-GCC",
            "Начальник ЦДУ", "General Control Center Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-234", "Чжиган", "Дуань", null, "Zhigang", "Duan", null, "duanzhigang@atg.uz", "94 660 61 72", "2590, 2535", "BMGMC-GCC",
            "Старший диспетчер ЦДУ", "Chief Dispatcher of GCC", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-235", "Бекзод", "Буриев", null, "Bekzod", "Buriev", null, "b.buriev@atg.uz", "94 660 30 56", "2310", "BMGMC-GCC",
            "Старший диспетчер ЦДУ", "Chief Dispatcher of GCC", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-236", "Лазиз", "Буронов", null, "Laziz", "Buronov", null, "l.buranov@atg.uz", "94 660 26 83", "2001, 2301", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-237", "Шакир", "Нажмидинов", null, "Shakir", "Najmidinov", null, "sh.najmidinov@atg.uz", "94 660 21 74", "2001, 2301", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-238", "Салохиддин", "Рустамов", null, "Saloxiddin", "Rustamov", null, "s.rustamov@atg.uz", "94 660 30 26", "2001, 2301", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-239", "Чжэчжэ", "Юй", null, "Zhezhe", "Yu", null, "yuzhezhe@atg.uz", "94 660 30 14", "2000, 2300, 2536", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-240", "Ли", "Ай", null, "Li", "Ai", null, "aili@atg.uz", "94 660 80 78", "2000, 2300, 2534", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-241", "Сергей", "Растворцев", null, "Sergey", "Rastvorcev", null, "s.rastvortsev@atg.uz", "94 660 30 61", "2001, 2301", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-242", "Сюэхуэй", "Сюй", null, "Xuehui", "Xu", null, "xuxuehui@atg.uz", "94 660 30 36", "2000, 2300", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-243", "Хань", "Ци", null, "Han", "Qi", null, "qihan@atg.uz", "94 660 05 25", "2000, 2300, 2531", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-244", "Чуньшэн", "Лян", null, "Chunsheng", "Liang", null, "liangchunsheng@atg.uz", "94 660 80 82", "2000, 2300, 2532", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-245", "Миршод", "Ибрагимов", null, "Mirshod", "Ibragimov", null, "m.ibragimov@atg.uz", "94 660 26 44", "2001, 2301", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-246", "Шухрат", "Шарипов", null, "Shukhrat", "Sharipov", null, "sh.sharipov@atg.uz", "94 660 08 58", "2001, 2301", "BMGMC-GCC",
            "Сменный инженер", "Shift Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-247", "Пу", "Чан", null, "Pu", "Chang", null, "changpu@atg.uz", "94 660 01 30", "2538", "BMGMC-GCC",
            "Специалист по учёту расхода газа", "Gas Metering Officer", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-248", "Артур", "Ким", null, "Artur", "Kim", null, "a.kim@atg.uz", "94 660 26 70", "2386", "BMGMC-GCC",
            "Специалист по учёту расхода газа", "Gas Metering Officer", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-249", "Бехруз", "Шарафов", null, "Bekhruz", "Sharafov", null, "b.sharafov@atg.uz", "94 660 98 35", "2386", "BMGMC-GCC",
            "Специалист по учёту расхода газа", "Gas Metering Officer", "SPECIALIST", UserRole.BMGMCEngineer),

        // Отдел по техническим вопросам / Technical Affairs Section
        new("ATG-250", "Цзинь", "Тао", null, "Jin", "Tao", null, "taojin@atg.uz", "94 660 31 34, 98 180 00 55", "2308, 2537", "BMGMC-TECH",
            "Начальник отдела по техническим вопросам", "Technical affairs section Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-251", "Тао", "Сунь", null, "Tao", "Sun", null, "suntao@atg.uz", "94 660 24 38", "2560", "BMGMC-TECH",
            "Заместитель начальника отдела по техническим вопросам", "Technical affairs section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-252", "Собир", "Тураев", null, "Sobir", "Turaev", null, "s.turaev@atg.uz", "94 660 01 17", "2375", "BMGMC-TECH",
            "Заместитель начальника отдела по техническим вопросам", "Technical affairs section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-253", "Артём", "Воробьёв", null, "Artyom", "Vorobyov", null, "a.vorobev@atg.uz", "94 888 17 30", "2356", "BMGMC-TECH",
            "Заместитель начальника отдела по техническим вопросам", "Technical affairs section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-254", "Янь", "Лю", null, "Yan", "Liu", null, "liuyan@atg.uz", "94 660 32 43", "2360, 2570", "BMGMC-TECH",
            "Инженер по компрессорам", "Compressors Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-255", "Шичжэн", "Тао", null, "Shizheng", "Tao", null, "taoshizheng@atg.uz", "94 660 26 63", "2360", "BMGMC-TECH",
            "Инженер по компрессорам", "Compressors engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-256", "Санжар", "Нурмуратов", null, "Sanjar", "Nurmuratov", null, "s.nurmuratov@atg.uz", "94 660 30 55", "2383", "BMGMC-TECH",
            "Инженер по компрессорам", "Compressors engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-257", "Сяо", "Фу", null, "Xiao", "Fu", null, "fuxiao@atg.uz", "94 660 21 71", "2585, 2571", "BMGMC-TECH",
            "Инженер-электрик", "Electrical Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-258", "Жура", "Мухаммадов", null, "Jura", "Muhammadov", null, "j.muhammadov@atg.uz", "94 660 26 07", "2585", "BMGMC-TECH",
            "Инженер-электрик", "Electrical Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-259", "Сюй", "Хэ", null, "Xu", "He", null, "hexu@atg.uz", "50 333 53 22", null, "BMGMC-TECH",
            "Инженер-электрик", "Electrical Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-260", "Ахрор", "Бахронов", null, "Akhror", "Bakhronov", null, "a.bakhronov@atg.uz", "94 888 23 60", "2585", "BMGMC-TECH",
            "Инженер-электрик по технической документации", "Electrical engineer for Technical Documentation", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-261", "Баходир", "Нарзуллоев", null, "Bakhodir", "Narzulloev", null, "b.narzulloev@atg.uz", "94 660 26 19", "2385", "BMGMC-TECH",
            "Инженер по механическому оборудованию", "Mechanics equipment engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-262", "Нодирбек", "Муродов", null, "Nodirbek", "Murodov", null, "n.murodov@atg.uz", "94 660 61 74", "2591", "BMGMC-TECH",
            "Инженер по механическому оборудованию", "Mechanics equipment engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-263", "Цзянь", "Лу", null, "Jian", "Lu", null, "liujian@atg.uz", "94 660 30 32", null, "BMGMC-TECH",
            "Инженер по механическому оборудованию", "Mechanics equipment engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-264", "Чао", "Чжан", null, "Chao", "Zhang", null, "zhangchao@atg.uz", "94 888 03 90", "2594", "BMGMC-TECH",
            "Инженер по плану технического обслуживания", "Maintenance Plan Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-265", "Рустам", "Абдуллаев", null, "Rustam", "Abdullaev", null, "r.abdullaev@atg.uz", "94 660 21 42", "2383", "BMGMC-TECH",
            "Инженер по плану технического обслуживания", "Maintenance Plan Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-266", "Гафур", "Самадов", null, "Gafur", "Samadov", null, "g.samadov@atg.uz", "94 660 80 89", "2508", "BMGMC-TECH",
            "Инженер по компрессорам и технической документации", "Compressors and Technical Documentation engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-267", "Усмон", "Бакаев", null, "Usmon", "Bakaev", null, "u.bakaev@atg.uz", "94 655 50 59", "2385", "BMGMC-TECH",
            "Инженер по механическому оборудованию и технической документации", "Mechanics equipment and Technical Documentation engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-268", "Амирбек", "Мусаев", null, "Amirbek", "Musaev", null, "a.musaev@atg.uz", "94 660 60 14", "2505", "BMGMC-TECH",
            "Инженер систем автоматического оборудования по технической документации", "Automatic Equipments System Engineer for Technical Documentation", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-269", "Абдулла", "Расулов", null, "Abdulla", "Rasulov", null, "a.rasulov@atg.uz", "94 660 30 19", "2046, 2056", "BMGMC-TECH",
            "Инженер-химик", "Chemist Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-270", "Гульшан", "Мардонова", null, "Gulshan", "Mardonova", null, "g.mardonova@atg.uz", "94 660 92 12", "2046", "BMGMC-TECH",
            "Аналитик", "Analyst", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-900", "Тест", "Пользователь", null, "Test", "User", null, "user1@atg.uz", null, null, "BMGMC-TECH",
            "Инженер TAS (тест)", "TAS Test Engineer", "ENGINEER", UserRole.BMGMCEngineer),

        // Отдел цифровизации и автоматизации / Digitalization and Automation Section
        new("ATG-271", "Сяонин", "Сун", null, "Xiaoning", "Song", null, "songxiaoning@atg.uz", "94 660 26 43", "2358, 2543", "BMGMC-ITDIG",
            "Начальник отдела цифровизации и автоматизации", "Digitalization and automation section Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-272", "Музаффар", "Нуров", null, "Muzaffar", "Nurov", null, "m.nurov@atg.uz", "94 660 31 21", "2370", "BMGMC-ITDIG",
            "Заместитель начальника отдела цифровизации и автоматизации", "Digitalization and automation section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-273", "Сюэвэнь", "Бянь", null, "Xuewen", "Bian", null, "bianxuewen@atg.uz", "94 660 30 18", "2589, 2577", "BMGMC-ITDIG",
            "Заместитель начальника отдела цифровизации и автоматизации", "Digitalization and automation section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-274", "Рахимжон", "Муминов", null, "Rakhimjon", "Muminov", null, "r.muminov@atg.uz", "94 660 50 58", "2593", "BMGMC-ITDIG",
            "Инженер SCADA", "SCADA Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-275", "Нуриддин", "Халимов", null, "Nuriddin", "Khalimov", null, "n.khalimov@atg.uz", "94 660 58 68", "2503", "BMGMC-ITDIG",
            "Инженер SCADA", "SCADA Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-276", "Цзянь", "Лю", null, "Jian", "Liu", null, "liu.jian@atg.uz", "93 111 23 97", null, "BMGMC-ITDIG",
            "Инженер SCADA", "SCADA Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-277", "Бобур", "Тухтамуродов", null, "Bobur", "Tukhtamurodov", null, "b.tukhtamurodov@atg.uz", "50 333 53 24", "2589", "BMGMC-ITDIG",
            "Инженер SCADA", "SCADA Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-278", "Чуньлун", "Чэнь", null, "Chunlong", "Chen", null, "chenchunlong@atg.uz", "94 660 22 51", "2345, 2563", "BMGMC-ITDIG",
            "Инженер по волоконно-оптической и спутниковой связи", "Fiber Optic and Satellite engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-279", "Шухрат", "Бобоев", null, "Shukhrat", "Boboev", null, "sh.boboev@atg.uz", "94 660 26 25", "2346", "BMGMC-ITDIG",
            "Инженер по волоконно-оптической и спутниковой связи", "Fiber Optic and Satellite engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-280", "Эркин", "Болтаев", null, "Erkin", "Boltaev", null, "e.boltayev@atg.uz", "94 660 22 98", "2348", "BMGMC-ITDIG",
            "Инженер IT и связи", "IT and communication Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-281", "Андрей", "Ризаев", null, "Andrey", "Rizaev", null, "a.rizaev@atg.uz", "94 660 24 68", "2314", "BMGMC-ITDIG",
            "Инженер IT и связи", "IT and communication Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-282", "Бихруз", "Тухтаев", null, "Bikhruz", "Tukhtaev", null, "b.tukhtaev@atg.uz", "93 180 09 14", "2581", "BMGMC-ITDIG",
            "Инженер IT и связи", "IT and communication Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-283", "Бахтийор", "Ибатов", null, "Bakhtiyor", "Ibatov", null, "b.ibatov@atg.uz", "93 555 22 90", "2581", "BMGMC-ITDIG",
            "Инженер IT и связи", "IT and communication Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-284", "Юцзе", "Вэй", null, "Yuze", "Wei", null, "weiyuze@atg.uz", "50 105 06 51", null, "BMGMC-ITDIG",
            "Инженер IT и связи", "IT and communication Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-285", "Шерали", "Жураев", null, "Sherali", "Juraev", null, "s.juraev@atg.uz", "94 660 26 29", "2210", "BMGMC-ITDIG",
            "Инженер-метролог (старший специалист)", "Metrology engineer (Senior specialist)", "SPECIALIST", UserRole.BMGMCEngineer),

        // Поверочная лаборатория / Calibration Laboratory
        new("ATG-286", "Шерзод", "Жураев", null, "Sherzod", "Juraev", null, "sh.juraev@atg.uz", "94 660 80 92", "2015", "BMGMC-CALIB",
            "Заведующий поверочной лабораторией (ведущий специалист)", "Head of Calibration Laboratory (Leading specialist)", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-287", "Анвар", "Тешаев", null, "Anvar", "Teshaev", null, "a.teshaev@atg.uz", "94 660 64 17", "2210", "BMGMC-CALIB",
            "Инженер-метролог (специалист) поверочной лаборатории", "Metrology engineer (specialist) of Calibration laboratory", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-288", "Вахобжон", "Рахимов", null, "Vakhobjon", "Rakhimov", null, "v.rahimov@atg.uz", "94 660 30 54", "6005, 6117", "BMGMC-CALIB",
            "Инженер-метролог (старший специалист) на объектах поверочной лаборатории", "Metrology engineer (Senior specialist) in facilities of Calibration laboratory", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-289", "Шахзод", "Баймуратов", null, "Shahzod", "Baymuratov", null, "sh.baymuratov@atg.uz", "50 122 06 34", "8117", "BMGMC-CALIB",
            "Инженер-метролог на объектах", "Metrology engineer in facilities", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-290", "Джамшид", "Иномов", null, "Jamshid", "Inomov", null, "j.inomov@atg.uz", "94 888 20 34", "3001", "BMGMC-CALIB",
            "Инженер-метролог на объектах (КС1, УКС1)", "Metrology Engineer in facilities (WKC1, UCS1)", "SPECIALIST", UserRole.BMGMCEngineer),

        // Центр ремонта и техобслуживания / Repair and Maintenance Center
        new("ATG-291", "Куян", "Сюй", null, "Kuoyang", "Xu", null, "xukuoyang@atg.uz", "93 505 65 69", "2068", "BMGMC-RMC",
            "Начальник центра ремонта и техобслуживания", "Repair and Maintenance Center Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-292", "Цзяцянь", "Хао", null, "Jiaqian", "Hao", null, "haojiaqian@atg.uz", "94 660 87 07", "2068", "BMGMC-RMC",
            "Заместитель начальника ЦР и ТО", "Repair and Maintenance Center Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-293", "Алишер", "Бахромов", null, "Alisher", "Bahromov", null, "a.bahromov@atg.uz", "94 660 21 79", "2034", "BMGMC-RMC",
            "Заместитель начальника ЦР и ТО", "Repair and Maintenance Center Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-294", "Сергей", "Тяпкин", null, "Sergey", "Tyapkin", null, "s.tyapkin@atg.uz", "94 660 21 35", "2072", "BMGMC-RMC",
            "Инженер-механик по оборудованию", "Mechanics equipment engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-295", "Баоли", "Цзинь", null, "Baoli", "Jing", null, "jingbaoli@atg.uz", "94 660 75 85", "2050", "BMGMC-RMC",
            "Инженер-механик по оборудованию", "Mechanics equipment engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-296", "Хунюй", "Чэнь", null, "Hongyu", "Chen", null, "chenhongyu@atg.uz", "94 888 03 56", "2028", "BMGMC-RMC",
            "Инженер-механик по оборудованию", "Mechanics equipment engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-297", "Гофур", "Розиков", null, "Gofur", "Rozikov", null, "g.rozikov@atg.uz", "93 555 46 75", "2059", "BMGMC-RMC",
            "Инженер-электрик", "Electrical Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-298", "Цзя", "Цуй", null, "Jia", "Cui", null, "cuijia@atg.uz", "50 333 03 27", "2050", "BMGMC-RMC",
            "Инженер-электрик", "Electrical Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-299", "Цзиньвэй", "Дуань", null, "Jinwei", "Duan", null, "duanjinwei@atg.uz", "93 555 46 89", null, "BMGMC-RMC",
            "Инженер по сварке", "Welding engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-300", "Хуршид", "Хикматов", null, "Khurshid", "Khikmatov", null, "kh.khikmatov@atg.uz", "94 818 61 62", "2065", "BMGMC-RMC",
            "Инженер по сварке", "Welding engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-301", "Алишер", "Гафуров", null, "Alisher", "Gafurov", null, "a.gafurov@atg.uz", "94 660 26 99", "2059", "BMGMC-RMC",
            "Техник-ремонтник", "Mechanic Repairman", "TECHNICIAN", UserRole.BMGMCEngineer),

        // Отдел по управлению трубопроводом / Pipeline Management Section
        new("ATG-302", "Вэй", "Хэ", null, "Wei", "He", null, "hewei@atg.uz", "94 660 23 78", "2390", "BMGMC-PIPE",
            "Начальник отдела по управлению трубопроводом", "Pipeline Management Section Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-303", "Рустам", "Икрамов", null, "Rustam", "Ikramov", null, "r.ikramov@atg.uz", "94 660 21 24", "2588", "BMGMC-PIPE",
            "Заместитель начальника отдела по управлению трубопроводом", "Pipeline Management Section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-304", "Жуй", "Хуан", null, "Rui", "Huang", null, "huangrui@atg.uz", "94 888 01 69", null, "BMGMC-PIPE",
            "Заместитель начальника отдела по управлению трубопроводом", "Pipeline Management Section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-305", "Кодиржон", "Раджабов", null, "Kodirjon", "Radjabov", null, "k.radjabov@atg.uz", "94 660 50 19", "2058", "BMGMC-PIPE",
            "Инженер ЭХЗ", "Electrochemical Protection Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-306", "Гуламхусейн", "Гасанов", null, "Gulamkhuseyn", "Gasanov", null, "g.gasanov@atg.uz", "94 660 26 58", "2579", "BMGMC-PIPE",
            "Инженер по управлению трубопровода", "Pipeline Management Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-307", "Пэнпэн", "Вэй", null, "Pengpeng", "Wei", null, "weipengpeng@atg.uz", "50 105 06 52", null, "BMGMC-PIPE",
            "Инженер по управлению трубопровода", "Pipeline Management Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-308", "Равшан", "Бафоев", null, "Ravshan", "Bafoev", null, "r.bafoev@atg.uz", "94 660 21 94", "2014", "BMGMC-PIPE",
            "Инженер по ликвидации аварийных ситуаций и управлению безопасностью трубопроводов", "Emergency response and pipeline safety management engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-309", "Юехун", "Ван", null, "Yuehong", "Wang", null, "wangyuehong@atg.uz", "94 660 80 71", null, "BMGMC-PIPE",
            "Инженер по ликвидации аварийных ситуаций и управлению безопасностью трубопроводов", "Emergency response and pipeline safety management engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-310", "Назир", "Муксинов", null, "Nazir", "Muksinov", null, "n.muksinov@atg.uz", "94 660 21 83", "2067", "BMGMC-PIPE",
            "Инженер по линейной части", "Pipeline Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-311", "Акрам", "Абдуллоев", null, "Akram", "Abdulloev", null, "a.abdulloev@atg.uz", "94 660 53 83", "2067", "BMGMC-PIPE",
            "Инженер по линейной части", "Pipeline Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-312", "Фаезжон", "Ибрагимов", null, "Fayozjon", "Ibragimov", null, "f.ibragimov@atg.uz", "94 660 95 12", "2579", "BMGMC-PIPE",
            "Инженер по линейной части", "Pipeline Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-313", "Элер", "Мурадов", null, "Elyor", "Muradov", null, "e.muradov@atg.uz", "94 660 21 23", "2014", "BMGMC-PIPE",
            "Инженер КИПиА", "Automatic Equipments System Engineer", "ENGINEER", UserRole.BMGMCEngineer),
        new("ATG-314", "Мехриддин", "Гуломов", null, "Mekhriddin", "Gulomov", null, "m.gulomov@atg.uz", "94 888 17 83", "2067", "BMGMC-PIPE",
            "Инженер-электрик", "Electrical Engineer", "ENGINEER", UserRole.BMGMCEngineer),

        // Отдел снабжения / Supply Section
        new("ATG-439", "Шихун", "Ван", null, "Shihong", "Wang", null, "wangshihong@atg.uz", "94 660 21 78", "2090, 2539", "BMGMC-SUP",
            "Начальник отдела снабжения", "Supply Section Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-440", "Шерали", "Кулдашев", null, "Sherali", "Kuldashev", null, "sh.kuldoshev@atg.uz", "94 660 23 51", "2026", "BMGMC-SUP",
            "Заместитель начальника отдела снабжения", "Supply Section Deputy Manager", "MANAGER", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-441", "Умиджон", "Гуломов", null, "Umidjon", "Gulomov", null, "u.gulomov@atg.uz", "94 660 71 09", "2061", "BMGMC-SUP",
            "Кладовщик", "Warehouse keeper", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-442", "Нурали", "Жумаев", null, "Nurali", "Jumaev", null, "n.jumayev@atg.uz", "94 660 59 09", "2061", "BMGMC-SUP",
            "Кладовщик", "Warehouse keeper", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-443", "Искандер", "Алиев", null, "Iskander", "Aliev", null, "i.aliev@atg.uz", "94 660 23 10", "2110", "BMGMC-SUP",
            "Кладовщик", "Warehouse keeper", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-444", "Шамшод", "Хакимов", null, "Shamshod", "Khakimov", null, "sh.khakimov@atg.uz", "94 660 73 23", "2011", "BMGMC-SUP",
            "Кладовщик", "Warehouse keeper", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-445", "Олим", "Нурматов", null, "Olim", "Nurmatov", null, "o.nurmatov@atg.uz", "94 660 21 52", "9090, 9015", "BMGMC-SUP",
            "Кладовщик (УУЗРГ)", "Warehouse keeper (UKMS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-446", "Зокир", "Нарзуллаев", null, "Zokir", "Narzullaev", null, "z.narzullaev@atg.uz", "94 660 86 96", "1010", "BMGMC-SUP",
            "Кладовщик (КС1 и УКС1)", "Warehouse keeper (WKC1 & UCS1)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-447", "Феруз", "Ганиев", null, "Feruz", "Ganiev", null, "f.ganiev@atg.uz", "94 660 52 82", "5013", "BMGMC-SUP",
            "Кладовщик (КС3)", "Warehouse keeper (WKC3)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-448", "Мирзоюсуф", "Сулейманов", null, "Mirzoyusuf", "Suleymanov", null, "m.suleymanov@atg.uz", "94 660 61 51", "8002", "BMGMC-SUP",
            "Кладовщик (КС2/ГКС)", "Warehouse keeper (WKC2/GCS)", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-449", "Бахром", "Бахронов", null, "Bakhrom", "Bakhronov", null, "b.bakhronov@atg.uz", "93 642 79 19", "4377", "BMGMC-SUP",
            "Кладовщик (УКС3)", "Warehouse keeper (UCS3)", "SPECIALIST", UserRole.BMGMCEngineer),

        // Вахтовое общежитие / Shift Dormitory
        new("ATG-450", "Гани", "Уринов", null, "Gani", "Urinov", null, "g.urinov@atg.uz", "94 660 30 27", null, "BMGMC-DORM",
            "Начальник комплекса", "Complex Manager", "NACHALNIK", UserRole.BMGMCNachalnikiOtdeli),
        new("ATG-451", "Улугбек", "Холов", null, "Ulugbek", "Kholov", null, "u.kholov@atg.uz", "93 555 46 90", null, "BMGMC-DORM",
            "Заведующий хозяйственной частью", "Household coordinator", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-452", "Баходир", "Абилхаиров", null, "Bahodir", "Abilhairov", null, "b.abilhairov@atg.uz", "94 660 26 15", null, "BMGMC-DORM",
            "Старший администратор (главный специалист) вахтового общежития", "Senior administrator (Chief specialist) of Shift Dormitory", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-453", "Фарух", "Норов", null, "Farukh", "Norov", null, "fa.norov@atg.uz", "94 660 21 17", null, "BMGMC-DORM",
            "Администратор стойки регистрации", "Receptionist", "SPECIALIST", UserRole.BMGMCEngineer),
        new("ATG-454", "Ситора", "Нуруллаева", null, "Sitora", "Nurullaeva", null, "si.nurullaeva@atg.uz", "94 660 60 27", null, "BMGMC-DORM",
            "Администратор стойки регистрации", "Receptionist", "SPECIALIST", UserRole.BMGMCEngineer),
    ];
}
