using ATG.Platform.Domain.Enums;

namespace ATG.Platform.Infrastructure.Seeds;

public record HoDepartment(string Code, string NameRu, string NameEn, string? ParentCode = null, bool Active = true);

public record StationStaffMember(
    string EmployeeId,
    string FirstNameRu,
    string LastNameRu,
    string? MiddleNameRu,
    string FirstNameEn,
    string LastNameEn,
    string? MiddleNameEn,
    string Email,
    string? Phone,
    string? InternalExt,
    string OrganizationCode,
    string DepartmentCode,
    string JobTitleRu,
    string JobTitleEn,
    string PositionCode,
    UserRole Role);

public record HoStaffMember(
    string EmployeeId,
    string FirstNameRu,
    string LastNameRu,
    string? MiddleNameRu,
    string FirstNameEn,
    string LastNameEn,
    string? MiddleNameEn,
    string Email,
    string? Phone,
    string? InternalExt,
    string DepartmentCode,
    string JobTitleRu,
    string JobTitleEn,
    string PositionCode,
    UserRole Role);

/// <summary>Tashkent Head Office org chart — bilingual RU/EN.</summary>
public static class HoMasterData
{
    public const string OrganizationCode = "HO";

    public static readonly HoDepartment[] Departments =
    [
        new("HO-EXEC", "Руководство", "Leaders"),
        new("HO-SEC", "Служба безопасности", "Security Service"),
        new("HO-AC", "Антикоррупционная Служба", "Anti-corruption Service"),
        new("HO-FINPLAN", "Департамент финансов и планирования", "Finance and Planning Department"),
        new("HO-ACCT", "Центральная бухгалтерия", "Accounting Center"),
        new("HO-ENGCON", "Департамент по инжинирингу и строительству", "Engineering and Construction Department"),
        new("HO-NEWPRJ", "Департамент по новым проектам", "New Projects Department"),
        new("HO-ITDIG", "Департамент по информационным технологиям и цифровизации", "IT & Digitalization Department"),
        new("HO-MKT", "Департамент по маркетингу и управлению тендерами", "Marketing and Tender Management Department"),
        new("HO-CPROC", "Департамент по контрактам и закупкам", "Contracts and Procurement Department"),
        new("HO-DCPR", "Департамент по документообороту и связям с общественностью", "Document Control and Public Relations Department"),
        new("HO-QHSE", "Департамент по качеству, технике безопасности и охране окружающей среды", "QHSE Department"),
        new("HO-GASM", "Департамент по учёту газа", "Gas Metering Department"),
        new("HO-LEGAL", "Юридический департамент", "Legal Department"),
        new("HO-HR", "Департамент по кадрам", "HR Department"),
        new("HO-ADM", "Департамент по административно-хозяйственным вопросам", "Administrative and Utility Issues Department"),
        new("HO-MKT-MKT", "Отдел маркетинга", "Marketing Section", "HO-MKT"),
        new("HO-MKT-TND", "Отдел тендеров", "Tender Section", "HO-MKT"),
        new("HO-CPROC-CADM", "Отдел по управлению контрактами", "Contracts Administration Section", "HO-CPROC"),
        new("HO-CPROC-DOM", "Отдел локальных закупок", "Domestic Procurement Section", "HO-CPROC"),
        new("HO-CPROC-INT", "Отдел международных закупок", "International Procurement Section", "HO-CPROC"),
        new("HO-DCPR-CLER", "Канцелярия", "Clerical Section", "HO-DCPR"),
        new("HO-DCPR-PR", "Отдел связей с общественностью", "Public Relations Section", "HO-DCPR"),
        new("HO-DCPR-TRNS", "Отдел технических переводов", "Technical Translations Section", "HO-DCPR"),
        new("HO-ADM-ADMIN", "Административный отдел", "Administrative Section", "HO-ADM"),
        new("HO-ADM-TRANS", "Транспортный отдел", "Transport Section", "HO-ADM"),
        new("HO-IT", "IT отдел", "IT Department", null, false),
        new("HO-PROC", "Отдел закупок", "Procurement", null, false),
        new("HO-OPS", "Производственно-технический отдел", "Operations", null, false),
        new("HO-ENG", "Инженерно-технический отдел", "Engineering", null, false),
        new("HO-HSE", "Охрана труда и техника безопасности", "HSE", null, false),
        new("HO-COMM", "Коммерческий отдел", "Commercial", null, false),
        new("HO-DCS", "Документооборот", "Document Control", null, false),
        new("HO-PLAN", "Планово-экономический отдел", "Planning & Economics", null, false),
        new("HO-QA", "Отдел качества", "Quality Assurance", null, false),
    ];

    public static readonly string[] LegacyDepartmentCodes = ["HO-SAF", "HO-FIN"];

    public static readonly HoStaffMember[] Staff =
    [
        // Руководство / Leaders
        new("ATG-002", "Чжигуан", "Лю", null, "Zhiguang", "Liu", null, "liuzhiguang@atg.uz", "90 966 78 87", "7899", "HO-EXEC",
            "Генеральный директор", "General Director", "TOP_MANAGER", UserRole.HOTopManager),
        new("ATG-003", "Миржалол", "Азизов", "Абдусаламович", "Mirjalol", "Azizov", "Abdusalamovich", "m.azizov@atg.uz", "93 700 00 66", "7599", "HO-EXEC",
            "Первый заместитель генерального директора", "First Deputy General Director", "TOP_MANAGER", UserRole.HOTopManager),
        new("ATG-004", "Собир", "Латипов", "Исаевич", "Sobir", "Latipov", "Isaevich", "s.latipov@atg.uz", "93 183 55 00", "7999", "HO-EXEC",
            "Заместитель генерального директора по проектированию и строительству", "Deputy General Director for Engineering and Construction", "TOP_MANAGER", UserRole.HOTopManager),
        new("ATG-005", "Айминь", "Тянь", null, "Aimin", "Tian", null, "tianaimin@atg.uz", "50 333 08 38", "7602", "HO-EXEC",
            "Заместитель генерального директора по новым проектам", "Deputy General Director for New Projects", "TOP_MANAGER", UserRole.HOTopManager),
        new("ATG-006", "Рустам", "Магзумов", "Хамидуллаевич", "Rustam", "Magzumov", "Khamidullaevich", "rm.magzumov@atg.uz", "94 660 24 82", "7515", "HO-EXEC",
            "Главный инспектор по новым проектам", "Chief Inspector for New Projects", "MANAGER", UserRole.HONachalnik),
        new("ATG-007", "Юн", "Ли", null, "Yong", "Li", null, "li.yong@atg.uz", "94 660 92 35", "7567", "HO-EXEC",
            "Заместитель генерального директора по коммерческим вопросам", "Deputy General Director for Commercial Affairs", "TOP_MANAGER", UserRole.HOTopManager),
        new("ATG-008", "Жахонгир", "Рахматуллаев", "Бахтиярович", "Jakhongir", "Rakhmatullaev", "Bakhtiyarovich", "j.rakhmatullaev@atg.uz", "94 777 07 55", "7622", "HO-EXEC",
            "Заместитель генерального директора по административным вопросам", "Deputy General Director for Administrative Affairs", "TOP_MANAGER", UserRole.HOTopManager),
        new("ATG-009", "Хайбо", "Цюй", null, "Haibo", "Cui", null, "cuihaibo@atg.uz", "94 655 19 16", "7777", "HO-EXEC",
            "Главный инспектор по административным вопросам", "Chief Administrative Inspector", "MANAGER", UserRole.HONachalnik),
        new("ATG-010", "Рустам", "Каршибаев", "Икрамович", "Rustam", "Karshibaev", "Ikramovich", "r.karshibaev@atg.uz", "94 777 05 85", "7537", "HO-EXEC",
            "Главный бухгалтер", "Chief Accountant", "MANAGER", UserRole.HONachalnik),
        new("ATG-011", "Яого", "Юй", null, "Yaoguo", "Yu", null, "yuyaoguo@atg.uz", "94 800 01 86", "7606", "HO-EXEC",
            "Главный инспектор по проектированию и строительству", "Chief Inspector for Engineering and Construction", "MANAGER", UserRole.HONachalnik),

        // Служба безопасности / Security Service
        new("ATG-012", "Фахриддин", "Максудов", "Тулибаевич", "Fakhriddin", "Maksudov", "Tulibaevich", "f.maksudov@atg.uz", "93 111 47 71", "7557", "HO-SEC",
            "Начальник службы безопасности", "Manager of Security Service", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-013", "Дильшод", "Джаббаров", "Адылович", "Dilshod", "Djapparov", "Adylovich", "d.djapparov@atg.uz", "50 122 03 68", "7679", "HO-SEC",
            "Инспектор по внутренней безопасности (старший специалист)", "Internal Security Inspector (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Антикоррупционная Служба / Anti-corruption Service
        new("ATG-014", "Чжаоюй", "Ли", null, "Zhaoyu", "Li", null, "lizhaoyu@atg.uz", "93 111 27 52", "7910", "HO-AC",
            "Главный координатор по антикоррупционной деятельности", "Chief Coordinator on Anti-Corruption", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-015", "Анвар", "Орипов", "Ахмаджанович", "Anvar", "Oripov", "Akhmadzhanovich", "a.oripov@atg.uz", "93 111 60 83", null, "HO-AC",
            "Ведущий специалист по антикоррупционной деятельности", "Leading specialist on Anti-Corruption", "SPECIALIST", UserRole.HOEngineer),

        // Департамент финансов и планирования / Finance and Planning
        new("ATG-016", "Фэн", "Ван", null, "Feng", "Wang", null, "wangfeng@atg.uz", "93 183 07 82", "7587", "HO-FINPLAN",
            "Начальник департамента финансов и планирования", "Manager of Finance and Planning Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-017", "Жалолиддин", "Ибодов", "Каромиддинович", "Jaloliddin", "Ibodov", "Karomiddinovich", "j.ibodov@atg.uz", "94 660 59 19", "7977", "HO-FINPLAN",
            "Заместитель начальника департамента финансов и планирования", "Deputy Manager of Finance and Planning Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-018", "Чэнюн", "Ло", null, "Chengyong", "Luo", null, "luochengyong@atg.uz", "93 111 27 30", "7587", "HO-FINPLAN",
            "Главный специалист по финансовым вопросам", "Financial Issues Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-019", "Цзяньхун", "Чэнь", null, "Jianhong", "Chen", null, "chenjianhong@atg.uz", "93 111 27 31", null, "HO-FINPLAN",
            "Главный специалист по финансовым вопросам", "Financial Issues Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-020", "Диёсбек", "Содиков", "Ахаджонович", "Diyosbek", "Sodikov", "Akhadjanovich", "d.sodikov@atg.uz", "93 111 60 19", "7951", "HO-FINPLAN",
            "Старший специалист по планированию затрат", "Cost Engineer (Senior specialist)", "ENGINEER", UserRole.HOEngineer),
        new("ATG-021", "Нодира", "Рихсибоева", null, "Nodira", "Rikhsiboeva", null, "n.rikhsiboeva@atg.uz", "94 660 06 75", "7571", "HO-FINPLAN",
            "Ведущий специалист по планированию затрат", "Cost Engineer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-022", "Тахир", "Таиров", "Шавкатович", "Takhir", "Tairov", "Shavkatovich", "t.tairov@atg.uz", "94 660 24 03", "7609", "HO-FINPLAN",
            "Главный специалист по ведению документации", "Documentation Processing Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-023", "Темурбек", "Кучимов", null, "Temurbek", "Kuchimov", null, "t.kuchimov@atg.uz", "94 744 47 07", null, "HO-FINPLAN",
            "Ведущий специалист по мониторингу инвестиций", "Leading specialist on Investment Monitoring", "SPECIALIST", UserRole.HOEngineer),

        // Центральная бухгалтерия / Accounting Center
        new("ATG-024", "Пэн", "Чжан", null, "Peng", "Zhang", null, "zhangpeng@atg.uz", "94 660 23 61", "7887", "HO-ACCT",
            "Начальник центральной бухгалтерии", "Manager of Accounting Center", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-025", "Азизбек", "Сафаров", "Авазхонович", "Azizbek", "Safarov", "Avazkhonovich", "a.safarov@atg.uz", "94 660 42 54", "7901", "HO-ACCT",
            "Заместитель начальника центральной бухгалтерии", "Deputy Manager of Accounting Center", "MANAGER", UserRole.HONachalnik),
        new("ATG-026", "Нодир", "Касымов", "Исмоилович", "Nodir", "Kasimov", "Ismoilovich", "n.kasimov@atg.uz", "94 660 23 83", "7538", "HO-ACCT",
            "Помощник начальника центральной бухгалтерии", "Manager Assistant of Accounting Center", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-027", "Дильфуза", "Убайдуллаева", "Зинатуллаевна", "Dilfuza", "Ubaydullaeva", "Zinatullaevna", "d.ubaydullaeva@atg.uz", "94 660 23 62", "7630", "HO-ACCT",
            "Материальный бухгалтер (главный специалист)", "Material Accountant (Chief Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-028", "Шахноза", "Кадырова", "Гайбуллаевна", "Shakhnoza", "Kadirova", "Gaibullaevna", "sh.kadirova@atg.uz", "93 590 70 50", "7788", "HO-ACCT",
            "Главный специалист центральной бухгалтерии", "Chief Specialist of Accounting Center", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-029", "Эльмира", "Биганова", "Адхамовна", "Elmira", "Biganova", "Adkhamovna", "e.biganova@atg.uz", "94 660 24 74", "7696", "HO-ACCT",
            "Бухгалтер оказанных услуг (главный специалист)", "Accountant of Rendered Services (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-030", "Алишер", "Абдурахмонов", "Ибраимкулович", "Alisher", "Abdurakhmonov", "Ibraimkulovich", "a.abdurakhmonov@atg.uz", "94 660 01 14", "7774", "HO-ACCT",
            "Бухгалтер оказанных услуг (ведущий специалист)", "Accountant of Rendered Services (Leading Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-031", "Шахло", "Шералиева", "Мамасаитовна", "Shakhlo", "Sheralieva", "Mamasaitovna", "sh.sheralieva@atg.uz", "94 660 99 80", "7640", "HO-ACCT",
            "Бухгалтер по внутренним счетам — кассир (старший специалист)", "Accountant (Senior specialist) on internal accounts - cashier", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-032", "Юйфэй", "Ли", null, "Yufei", "Li", null, "liyufei@atg.uz", "93 505 52 21", null, "HO-ACCT",
            "Бухгалтер по капитальным затратам и инвестициям (специалист)", "Capital costs and investments accountant (Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-033", "Сичэн", "Лю", null, "Xicheng", "Liu", null, "liuxicheng@atg.uz", "94 660 64 08", null, "HO-ACCT",
            "Бухгалтер по капитальным затратам и инвестициям (специалист)", "Capital costs and investments accountant (Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-034", "Нариман", "Казимов", null, "Nariman", "Kazimov", null, "n.kazimov@atg.uz", "94 660 22 48", "7539", "HO-ACCT",
            "Бухгалтер оказанных услуг (главный специалист)", "Accountant of Rendered Services (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-035", "Нозимахон", "Махмудова", "Адилжановна", "Nozimakhon", "Makhmudova", "Adilzhanovna", "n.makhmudova@atg.uz", "94 660 97 89", null, "HO-ACCT",
            "Материальный бухгалтер (ведущий специалист)", "Material Accountant (Leading Specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Департамент по инжинирингу и строительству / Engineering and Construction
        new("ATG-036", "Жамшид", "Юнусов", "Хамиджанович", "Jamshid", "Yunusov", "Khamidzhanovich", "j.yunusov@atg.uz", "94 660 21 89", "7787", "HO-ENGCON",
            "Начальник департамента по инжинирингу и строительству", "Manager of Engineering and Construction Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-037", "Вэй", "Го", null, "Wei", "Guo", null, "guowei@atg.uz", "94 660 23 76", "7747", "HO-ENGCON",
            "Заместитель начальника департамента по инжинирингу и строительству", "Deputy Manager of Engineering and Construction Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-038", "Бехзод", "Акбарходжаев", "Абдулхаевич", "Bekhzod", "Akbarkhodjaev", "Abdulkhaevich", "b.akbarkhodjaev@atg.uz", "94 660 23 36", "7727", "HO-ENGCON",
            "Заместитель начальника департамента по инжинирингу и строительству", "Deputy Manager of Engineering and Construction Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-039", "Азиз", "Ибраймов", "Русланович", "Aziz", "Ibraymov", "Ruslanovich", "a.ibraymov@atg.uz", "94 660 91 02", "7737", "HO-ENGCON",
            "Ведущий специалист по инжиниринговой и технологической поддержке", "Leading specialist on Engineering and Technology Support", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-040", "Тао", "Юй", null, "Tao", "Yu", null, "yutao@atg.uz", "94 744 07 60", null, "HO-ENGCON",
            "Координатор (ведущий специалист) по управлению проектами", "Coordinator (Leading specialist) on Project Management", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-041", "Сайдуллохон", "Мирзаабдуллаев", "Махамаджанович", "Saydullohon", "Mirzaabdullaev", "Makhamadzhanovich", "s.mirzaabdullaev@atg.uz", "94 660 24 11", "7757", "HO-ENGCON",
            "Инженер-строитель (главный специалист) по производственно-техническим вопросам", "Construction engineer (Chief specialist) for production and technical issues", "ENGINEER", UserRole.HOEngineer),
        new("ATG-042", "Дина", "Мухитдинова", "Рустамовна", "Dina", "Mukhitdinova", "Rustamovna", "d.mukhitdinova@atg.uz", "94 660 69 74", "7797", "HO-ENGCON",
            "Специалист по контролю стоимости проектирования и строительства (старший специалист)", "Design and Construction Cost Control Officer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-043", "Ирина", "Тян", "Ильинична", "Irina", "Tyan", "Ilyinichna", "i.tyan@atg.uz", "94 660 23 38", "7717", "HO-ENGCON",
            "Специалист по контролю стоимости проектирования и строительства (главный специалист)", "Design and Construction Cost Control Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-044", "Илхомжон", "Хамроев", "Исраилович", "Ilkhomjon", "Khamroev", "Israilovich", "i.khamroev@atg.uz", "94 660 02 28", null, "HO-ENGCON",
            "Инженер-строитель (ведущий специалист) по производственно-техническим вопросам", "Construction engineer (Leading specialist) for production and technical issues", "ENGINEER", UserRole.HOEngineer),
        new("ATG-045", "Кристина", "Депутатова", null, "Kristina", "Deputatova", null, "k.deputatova@atg.uz", "93 111 81 03", "7767", "HO-ENGCON",
            "Инженер по стоимости строительства (ведущий специалист)", "Construction Cost Engineer (Leading specialist)", "ENGINEER", UserRole.HOEngineer),
        new("ATG-046", "Миразиз", "Адилов", null, "Miraziz", "Adilov", null, "m.adilov@atg.uz", "94 660 22 94 / 203 11 88", "7527", "HO-ENGCON",
            "Главный специалист по ведению документации", "Documentation Processing Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Департамент по новым проектам / New Projects Department
        new("ATG-047", "Жуйхуа", "Чжу", null, "Ruihua", "Zhu", null, "zhuruihua@atg.uz", "94 660 24 36", "7690", "HO-NEWPRJ",
            "Начальник департамента по новым проектам", "Manager of New Projects Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-048", "Шароф", "Алланазаров", "Атаназарович", "Sharof", "Allanazarov", "Atanazarovich", "sh.allanazarov@atg.uz", "94 660 79 03", "7658", "HO-NEWPRJ",
            "Заместитель начальника департамента по новым проектам", "Deputy Manager of New Projects Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-049", "Тимур", "Гинатулин", "Ринатович", "Timur", "Ginatulin", "Rinatovich", "t.ginatulin@atg.uz", "94 660 01 85", "7523", "HO-NEWPRJ",
            "Инженер по телекоммуникациям (ведущий специалист)", "Telecommunications Engineer (Leading specialist)", "ENGINEER", UserRole.HOEngineer),
        new("ATG-050", "Зумрад", "Джураева", "Холдаралиевна", "Zumrad", "Djuraeva", "Kholdaralievna", "z.djuraeva@atg.uz", "94 660 22 16", "7556", "HO-NEWPRJ",
            "Специалист по ведению документации (старший специалист)", "Documentation Processing Officer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-051", "Феруза", "Икрамова", "Ибрагимжановна", "Feruza", "Ikramova", "Ibragimzhanovna", "f.ikramova@atg.uz", "94 660 80 58", "7723", "HO-NEWPRJ",
            "Ведущий специалист по мониторингу инвестиций", "Leading specialist on Investment Monitoring", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-052", "Юн", "Ли", null, "Yong", "Li", null, "liyong@atg.uz", "94 660 24 40", "7737", "HO-NEWPRJ",
            "Специалист по контролю затрат (главный специалист)", "Cost Control Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-053", "Хамидулла", "Холмухамедов", "Хабибуллаевич", "Khamidulla", "Kholmukhamedov", "Khabibullaevich", "h.holmukhamedov@atg.uz", "94 660 11 83", "7565", "HO-NEWPRJ",
            "Инженер по телекоммуникациям (старший специалист)", "Telecommunications Engineer (Senior specialist)", "ENGINEER", UserRole.HOEngineer),
        new("ATG-054", "Одилбек", "Матчанов", null, "Odilbek", "Matchanov", null, "o.matchanov@atg.uz", "94 660 26 11", "7510", "HO-NEWPRJ",
            "Главный специалист по мониторингу инвестиций", "Chief specialist on Investment Monitoring", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-055", "Пэн", "Сунь", null, "Peng", "Sun", null, "sunpeng@atg.uz", "50 177 15 91", null, "HO-NEWPRJ",
            "Инженер по телекоммуникациям (главный специалист)", "Telecommunications Engineer (Chief specialist)", "ENGINEER", UserRole.HOEngineer),

        // IT & Digitalization Department
        new("ATG-056", "Анатолий", "Лебедев", "Валерьевич", "Anatoliy", "Lebedev", "Valerievich", "a.lebedev@atg.uz", "94 660 22 90", "7667", "HO-ITDIG",
            "Заместитель начальника департамента ИТ и цифровизации", "Deputy Manager of IT & Digitalization Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-057", "Эмиль", "Шазамов", "Эрнстович", "Emil", "Shazamov", "Ernstovich", "e.shazamov@atg.uz", "94 660 22 99", "7535", "HO-ITDIG",
            "Специалист по информационной безопасности (главный специалист)", "Information Security Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-058", "Арсен", "Минин", "Русланович", "Arsen", "Minin", "Ruslanovich", "a.minin@atg.uz", "94 777 43 33", "7677", "HO-ITDIG",
            "Специалист по информационной безопасности (специалист)", "Information Security Officer (Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-059", "Анвар", "Халилов", "Пулатович", "Anvar", "Khalilov", "Pulatovich", "a.khalilov@atg.uz", "94 655 58 55", "7666", "HO-ITDIG",
            "Специалист по ИТ (ведущий специалист)", "IT Officer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-060", "Пэн", "У", null, "Peng", "Wu", null, "wupeng@atg.uz", "50 333 05 63", null, "HO-ITDIG",
            "Специалист по ИТ (специалист)", "IT Officer (Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-061", "Азиз", "Кучкаров", "Шухратович", "Aziz", "Kuchkarov", "Shukhratovich", "a.kuchkarov@atg.uz", "94 660 91 93", "7808", "HO-ITDIG",
            "Специалист по ИТ (старший специалист)", "IT Officer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Marketing and Tender Management Department
        new("ATG-062", "Шубао", "Пан", null, "Shubao", "Pang", null, "pangshubao@atg.uz", "97 701 31 39", "7799", "HO-MKT",
            "Начальник департамента по маркетингу и управлению тендерами", "Manager of Marketing and Tender Management Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-063", "Жасурбек", "Зокиров", "Шоятжонович", "Jasurbek", "Zokirov", "Shoyatzhonovich", "j.zokirov@atg.uz", "93 111 60 84", "7950", "HO-MKT",
            "Заместитель начальника департамента по маркетингу и управлению тендерами", "Deputy Manager of Marketing and Tender Management Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-064", "Артур", "Мадрахимов", "Бахтиёрович", "Artur", "Madrakhimov", "Bakhtiyarovich", "a.madrakhimov@atg.uz", "94 744 08 16", "7997", "HO-MKT-MKT",
            "Начальник отдела маркетинга", "Marketing Section Manager", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-065", "Фарходжон", "Исроилов", "Шукурилло угли", "Farkhodjon", "Isroilov", "Shukurillo ugli", "f.isroilov@atg.uz", "94 660 64 67", "7555", "HO-MKT-MKT",
            "Ведущий специалист по маркетингу", "Marketing Leading specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-066", "Вэньтай", "Гао", null, "Wentai", "Gao", null, "gaowentai@atg.uz", "94 800 18 81", "7888", "HO-MKT-MKT",
            "Специалист по маркетингу", "Marketing Specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-067", "Дилшодхужа", "Темиров", "Шухратбекович", "Dilshod", "Temirov", "Shukhratbekovich", "d.temirov@atg.uz", "94 660 50 56", "7955", "HO-MKT-MKT",
            "Ведущий специалист по маркетингу", "Marketing Leading specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-068", "Фаррухбек", "Таваккалжонов", "Шерзодбек угли", "Farrukhbek", "Tavakkaljonov", "Sherzodbek ugli", "f.tavakkaljonov@atg.uz", "93 111 06 89", "7877", "HO-MKT-MKT",
            "Специалист по маркетингу", "Marketing Specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-069", "Сухробхужа", "Рустамхонов", "Музаффархон угли", "Sukhrobkhuja", "Rustamkhonov", "Muzaffarkhon ugli", "s.rustamkhonov@atg.uz", "93 111 64 21", "7665", "HO-MKT-MKT",
            "Специалист по маркетингу", "Marketing Specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-070", "Кирилл", "Дручинин", "Александрович", "Kirill", "Druzhinin", "Alexandrovich", "k.druchinin@atg.uz", "50 122 80 32", null, "HO-MKT-MKT",
            "Специалист по маркетингу", "Marketing Specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-901", "Тест", "Пользователь", "2", "Test", "User", "Two", "user2@atg.uz", null, null, "HO-MKT-MKT",
            "Начальник отдела маркетинга (тест)", "Marketing Section Manager (test)", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-071", "Инна", "Когай", "Артуровна", "Inna", "Kogay", "Arturovna", "i.kogay@atg.uz", "94 660 42 55", "7984", "HO-MKT-TND",
            "Специалист по тендерам (главный специалист)", "Tender Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-072", "Светлана", "Ким", "Михайловна", "Svetlana", "Kim", "Mikhailovna", "s.kim@atg.uz", "94 660 98 19", "7978", "HO-MKT-TND",
            "Специалист по тендерам (главный специалист)", "Tender Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Contracts and Procurement Department
        new("ATG-073", "Феруз", "Асадов", "Хасанович", "Feruz", "Asadov", "Khasanovich", "f.asadov@atg.uz", "93 501 00 17", "7800", "HO-CPROC",
            "Начальник департамента по контрактам и закупкам", "Manager of Contracts and Procurement Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-074", "Вэйцзянь", "Ван", null, "Weijian", "Wang", null, "wangweijian@atg.uz", "94 660 56 08", "7911", "HO-CPROC",
            "Заместитель начальника департамента по контрактам и закупкам", "Deputy Manager of Contracts and Procurement Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-075", "Ойбек", "Туляганов", "Мухтарович", "Oybek", "Tulyaganov", "Mukhtarovich", "o.tulyaganov@atg.uz", "94 660 22 45", "7558", "HO-CPROC",
            "Специалист по логистике и таможенному оформлению (главный специалист)", "Logistics and customs clearance Officer (Chief Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-076", "Луиза", "Бузрукова", "Рустамовна", "Luiza", "Buzrukova", "Rustamovna", "l.buzrukova@atg.uz", "94 660 23 58", "7656", "HO-CPROC",
            "Специалист по информации и аналитике (главный специалист)", "Information and Analytics Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-077", "Абдулла", "Ёдгоров", "Эркинович", "Abdulla", "Yodgorov", "Erkinovich", "a.yodgorov@atg.uz", "94 660 65 15", null, "HO-CPROC",
            "Специалист по логистике и таможенному оформлению (ведущий специалист)", "Logistics and Customs Clearance Officer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-078", "Мао", "Чжао", null, "Mao", "Zhao", null, "zhaomao@atg.uz", "93 183 14 90", null, "HO-CPROC-CADM",
            "Начальник отдела по управлению контрактами", "Contracts Administration Section Manager", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-079", "Абдувахид", "Абдухакимов", "Дильшадович", "Abduvakhid", "Abdukhakimov", "Dilshadovich", "a.abdukhakimov@atg.uz", "94 660 23 48", "7529", "HO-CPROC-CADM",
            "Специалист по управлению контрактами (старший специалист)", "Contracts Administration Officer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-080", "Собитхон", "Мирзаев", "Алишерович", "Sobitkhon", "Mirzaev", "Alisherovich", "s.mirzaev@atg.uz", "50 333 05 83", null, "HO-CPROC-CADM",
            "Специалист по управлению контрактами (ведущий специалист)", "Contracts Administration Officer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-081", "Руслан", "Масалимов", null, "Ruslan", "Masalimov", null, "r.masalimov@atg.uz", "94 744 32 57", "7570", "HO-CPROC-CADM",
            "Специалист по управлению контрактами (ведущий специалист)", "Contracts Administration Officer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-082", "Абдулазиз", "Низамов", null, "Abdulaziz", "Nizamov", null, "a.nizamov@atg.uz", "94 660 24 90", "7700", "HO-CPROC-CADM",
            "Специалист по управлению контрактами (главный специалист)", "Contracts Administration Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-083", "Расулбек", "Авезов", "Атабаевич", "Rasulbek", "Avezov", "Atabaevich", "r.avezov@atg.uz", "94 660 26 04", "7909", "HO-CPROC-DOM",
            "Начальник отдела локальных закупок", "Domestic Procurement Section Manager", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-084", "Бобуржон", "Валижонов", "Фарход угли", "Boburjon", "Valijonov", "Farhod ugli", "b.valijonov@atg.uz", "94 660 19 91", "7776", "HO-CPROC-DOM",
            "Специалист по закупкам (ведущий специалист)", "Procurement Officer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-085", "Аъзам", "Ачилов", "Шакиржонович", "Azam", "Achilov", "Shakirzhonovich", "a.achilov@atg.uz", "50 333 05 12", "7600", "HO-CPROC-DOM",
            "Специалист по закупкам (ведущий специалист)", "Procurement Officer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-086", "Азизхон", "Неъматхонов", "Хамидилло угли", "Azizkhon", "Nematkhonov", "Khamidillo ugli", "a.nematkhonov@atg.uz", "50 122 18 73", "7710", "HO-CPROC-DOM",
            "Специалист по закупкам (главный специалист)", "Procurement Officer (Chief Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-087", "Илхом", "Раимжанов", "Бахадиржанович", "Ilkhom", "Raimjanov", "Bakhadirzhanovich", "i.raimjanov@atg.uz", "97 701 36 56", "7564", "HO-CPROC-INT",
            "Начальник отдела международных закупок", "International Procurement Section Manager", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-088", "Геннадий", "Цоин", "Николаевич", "Gennadiy", "Tsoin", "Nikolaevich", "g.tsoin@atg.uz", "94 660 24 71", "7668", "HO-CPROC-INT",
            "Специалист по закупкам (главный специалист)", "Procurement Officer (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-089", "Яцзюнь", "Гао", null, "Yajun", "Gao", null, "gaoyajun@atg.uz", "93 505 52 27", null, "HO-CPROC-INT",
            "Специалист по закупкам (специалист)", "Procurement Officer (Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-090", "Нозимахон", "Рахматуллаева", "Алишеровна", "Nozimakhon", "Rakhmatullaeva", "Alisherovna", "n.rakhmatullaeva@atg.uz", "94 744 16 55", "7566", "HO-CPROC-INT",
            "Специалист по закупкам (ведущий специалист)", "Procurement Officer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Document Control and Public Relations Department
        new("ATG-091", "Чжэн", "Сяо", null, "Zheng", "Xiao", null, "xiaozheng@atg.uz", "93 183 14 13", "7518", "HO-DCPR",
            "Начальник департамента по документообороту и связям с общественностью", "Manager of Document Control and Public Relations Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-092", "Наталья", "Ким", "Алексеевна", "Natalya", "Kim", "Alexeevna", "n.kim@atg.uz", "97 701 12 05", "7543", "HO-DCPR",
            "Заместитель начальника департамента по документообороту и связям с общественностью", "Deputy Manager of Document Control and Public Relations Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-093", "Азиза", "Хасанова", null, "Aziza", "Khasanova", null, "a.khasanova@atg.uz", "94 660 23 57 / 203 11 99", "7603", "HO-DCPR",
            "Помощник руководителя (главный специалист)", "Executive Assistant (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-094", "Фаттох", "Сайдалиев", null, "Fattokh", "Saydaliev", null, "f.saydaliev@atg.uz", "94 777 06 84 / 203 11 77", "7601", "HO-DCPR",
            "Помощник руководителя (ведущий специалист)", "Executive Assistant (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-095", "Сяньбо", "Лю", null, "Xianbo", "Liu", null, "liuxianbo@atg.uz", "94 655 76 86", null, "HO-DCPR-CLER",
            "Начальник канцелярии", "Manager of Clerical Section", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-096", "Надежда", "Цой", "Николаевна", "Nadejda", "Tsoy", "Nikolaevna", "n.tsoy@atg.uz", "94 660 24 66", null, "HO-DCPR-CLER",
            "Инженер по документообороту (ведущий специалист)", "Document Control Engineer (Leading Specialist)", "ENGINEER", UserRole.HOEngineer),
        new("ATG-097", "Марина", "Югай", "Викторовна", "Marina", "Yugay", "Viktorovna", "m.yugay@atg.uz", "94 660 23 90", "7610", "HO-DCPR-CLER",
            "Инженер по документообороту (старший специалист)", "Document Control Engineer (Senior Specialist)", "ENGINEER", UserRole.HOEngineer),
        new("ATG-098", "Лиля", "Ахтамбаева", "Исамиддиновна", "Lilya", "Akhtambaeva", "Isamiddinovna", "l.akhtambaeva@atg.uz", "94 660 24 87", null, "HO-DCPR-CLER",
            "Архивариус (ведущий специалист)", "Archivist (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-099", "Ивэй", "Сунь", null, "Yiwei", "Sun", null, "sunyiwei@atg.uz", "50 122 78 17", null, "HO-DCPR-CLER",
            "Инженер по документообороту (опытный специалист)", "Document Control Engineer (Experienced specialist)", "ENGINEER", UserRole.HOEngineer),
        new("ATG-100", "Диана", "Елькибаева", "Вячеславовна", "Diana", "Elkibaeva", "Vyacheslavovna", "d.elkibaeva@atg.uz", "94 660 24 26", "7707", "HO-DCPR-PR",
            "Главный специалист по связям с общественностью", "PR Chief Specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-101", "Сишань", "Чжао", null, "Xishan", "Zhao", null, "zhaoxishan@atg.uz", "93 505 04 93", null, "HO-DCPR-PR",
            "Специалист по связям с общественностью", "PR Specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-102", "Замира", "Ташева", null, "Zamira", "Tasheva", null, "z.tasheva@atg.uz", "50 177 14 30", null, "HO-DCPR-PR",
            "Старший специалист по связям с общественностью", "PR Senior specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-103", "Шомурод", "Абдуллаев", null, "Shomurod", "Abdullaev", null, "sh.abdullaev@atg.uz", "93 111 81 02", null, "HO-DCPR-PR",
            "Специалист по связям с общественностью", "PR Specialist", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-104", "Сурьят", "Адамбаев", "Азаматович", "Surat", "Adambaev", "Azamatovich", "s.adambaev@atg.uz", "94 660 22 97", "7607", "HO-DCPR-TRNS",
            "Начальник отдела технических переводов", "Manager of Technical Translations Section", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-105", "Наргиза", "Абуталипова", "Суннатуллаевна", "Nargiza", "Abutalipova", "Sunnatullaevna", "n.abutalipova@atg.uz", "94 660 24 30", null, "HO-DCPR-TRNS",
            "Переводчик (главный специалист)", "Translator (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-106", "Дилмурод", "Гафуров", "Юсупджонович", "Dilmurod", "Gafurov", "Yusupdzhanovich", "d.gafurov@atg.uz", "94 660 24 60", null, "HO-DCPR-TRNS",
            "Переводчик (главный специалист)", "Translator (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-107", "Илхом", "Исмаилов", "Ирсматович", "Ilkhom", "Ismailov", "Irsmatovich", "i.ismailov@atg.uz", "94 660 24 64", "7582", "HO-DCPR-TRNS",
            "Переводчик (главный специалист)", "Translator (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-108", "Лола", "Кадырова", "Бахтиёровна", "Lola", "Kadyrova", "Bakhtiyarovna", "l.kadyrova@atg.uz", "94 660 65 56", null, "HO-DCPR-TRNS",
            "Переводчик (старший специалист)", "Translator (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-109", "Нигорахон", "Розбакиева", "Баходир кизи", "Nigorakhon", "Rozbakieva", "Bakhodir kizi", "n.rozbakieva@atg.uz", "94 777 02 61", "7654", "HO-DCPR-TRNS",
            "Переводчик (специалист)", "Translator (Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-110", "Виктор", "Хон", "Александрович", "Viktor", "Khon", "Alexandrovich", "v.khon@atg.uz", "50 122 06 39", null, "HO-DCPR-TRNS",
            "Переводчик (главный специалист)", "Translator (Chief specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-111", "Цзиньдин", "Ши", null, "Jinding", "Shi", null, "shijinding@atg.uz", "94 660 56 50", null, "HO-DCPR-TRNS",
            "Переводчик (ведущий специалист)", "Translator (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-112", "Чжици", "Шао", null, "Zhiqi", "Shao", null, "shaozhiqi@atg.uz", "50 177 67 98", null, "HO-DCPR-TRNS",
            "Переводчик (опытный специалист)", "Translator (Experienced specialist)", "SPECIALIST", UserRole.HOEngineer),

        // QHSE Department
        new("ATG-113", "Зебо", "Маннанова", "Манноновна", "Zebo", "Mannanova", "Mannonovna", "z.mannanova@atg.uz", "94 660 24 77", "7531", "HO-QHSE",
            "Начальник департамента QHSE", "Manager of QHSE Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-114", "Ган", "Цзинь", null, "Gang", "Jin", null, "jingang@atg.uz", "50 177 17 80", "7580", "HO-QHSE",
            "Заместитель начальника департамента QHSE", "Deputy Manager of QHSE Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-115", "Рим", "Алабердин", "Рафхатович", "Rim", "Alaberdin", "Rafkhatovich", "r.alaberdin@atg.uz", "50 122 03 69", "7577", "HO-QHSE",
            "Главный специалист СМК департамента QHSE", "IMS Chief Specialist of QHSE Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-116", "Зоирбек", "Болтаев", "Хасанович", "Zoirbek", "Boltayev", "Khasanovich", "z.boltaev@atg.uz", "94 660 22 67", "7532", "HO-QHSE",
            "Инспектор по безопасности и качеству (главный специалист)", "Safety and Quality Inspector (Chief Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-117", "Юймин", "Хуан", null, "Yuming", "Huang", null, "huangyuming@atg.uz", "94 777 19 28", null, "HO-QHSE",
            "Инспектор по безопасности и качеству (специалист)", "Safety and Quality Inspector (Specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-118", "Или", "Тан", null, "Yili", "Tang", null, "tangyili@atg.uz", "93 180 09 15", null, "HO-QHSE",
            "Инспектор по безопасности и качеству (специалист)", "Safety and Quality Inspector (Specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Gas Metering Department
        new("ATG-119", "Чжунхуа", "Цю", null, "Zhonghua", "Qiu", null, "qiuzhonghua@atg.uz", "94 655 02 40", "7563", "HO-GASM",
            "Начальник департамента по учёту газа", "Manager of Gas Metering Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-120", "Нуриддин", "Исмаилов", "Дурмишханович", "Nuriddin", "Ismailov", "Durmishkhanovich", "n.ismailov@atg.uz", "94 660 24 34", "7771", "HO-GASM",
            "Заместитель начальника департамента по учёту газа", "Deputy Manager of Gas Metering Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-121", "Даврон", "Адилов", "Сакиевич", "Davron", "Adilov", "Sakievich", "d.adilov@atg.uz", "97 701 09 08", "7770", "HO-GASM",
            "Помощник начальника департамента по учёту газа", "Manager Assistant of Gas Metering Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-122", "Нодир", "Юнусов", "Тахирович", "Nodir", "Yunusov", "Takhirovich", "n.yunusov@atg.uz", "94 660 24 22", "7773", "HO-GASM",
            "Специалист по управлению учётом (старший специалист)", "Metering Management Officer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-123", "Бахтиёр", "Джураев", "Хасанович", "Bakhtiyor", "Djuraev", "Khasanovich", "b.djuraev@atg.uz", "94 660 32 35", "7878", "HO-GASM",
            "Метролог (старший специалист)", "Metrologist (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-124", "Хэнцзюй", "Ван", null, "Hengju", "Wang", null, "wanghengju@atg.uz", "94 818 67 16", null, "HO-GASM",
            "Специалист по управлению учётом (опытный специалист)", "Metering Management Officer (Experienced specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-125", "Азиз", "Норматов", "Абдувалиевич", "Aziz", "Normatov", "Abduvalievich", "a.normatov@atg.uz", "94 660 24 14", "7772", "HO-GASM",
            "Специалист по допуску технологического газа (старший специалист)", "Process Gas Clearance Officer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),

        // Legal Department
        new("ATG-126", "Худайберди", "Нарбаев", "Халдыбекович", "Khudayberdi", "Narbaev", "Khaldybekovich", "h.narbaev@atg.uz", "97 732 77 00", "7500", "HO-LEGAL",
            "Начальник юридического департамента", "Manager of Legal Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-127", "Лян", "Чжоу", null, "Liang", "Zhou", null, "zhouliang@atg.uz", "94 655 78 68", "7526", "HO-LEGAL",
            "Заместитель начальника юридического департамента", "Deputy Manager of Legal Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-128", "Ильхом", "Эшонкулов", "Исроилвич", "Ilkhom", "Eshonkulov", "Isroilvich", "i.eshonkulov@atg.uz", "93 184 95 90", "7890", "HO-LEGAL",
            "Юрист (старший специалист)", "Lawyer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-129", "Лола", "Абдуллаева", "Хамидовна", "Lola", "Abdullaeva", "Khamidovna", "l.abdullaeva@atg.uz", "93 111 69 91", "7811", "HO-LEGAL",
            "Юрист (старший специалист)", "Lawyer (Senior specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-130", "Шии", "Чэнь", null, "Shiyi", "Chen", null, "chenshiyi@atg.uz", "93 111 27 32", null, "HO-LEGAL",
            "Юрист (ведущий специалист)", "Lawyer (Leading specialist)", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-131", "Юаньбо", "Ван", null, "Yuanbo", "Wang", null, "wangyuanbo@atg.uz", "50 333 08 37", null, "HO-LEGAL",
            "Специалист по ведению документации (специалист)", "Documentation Processing Officer (Specialist)", "SPECIALIST", UserRole.HOEngineer),

        // HR Department
        new("ATG-132", "Васильжон", "Хусенов", "Келдиёрович", "Vasiljon", "Khusenov", "Keldiyorovich", "v.khusenov@atg.uz", "94 660 32 42", "7900", "HO-HR",
            "Начальник департамента по кадрам", "Manager of HR Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-133", "Шо", "Ли", null, "Shuo", "Li", null, "lishuo@atg.uz", "93 111 69 92", "7505", "HO-HR",
            "Заместитель начальника департамента по кадрам", "Deputy Manager of HR Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-134", "Гульсара", "Рахматуллаева", "Абдумаликовна", "Gulsara", "Rakhmatullaeva", "Abdumalikovna", "g.rakhmatullaeva@atg.uz", "94 660 23 63", "7516", "HO-HR",
            "Помощник начальника департамента по кадрам", "Manager Assistant of Human Resources Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-135", "Ахат", "Хамроев", "Асатулло угли", "Akhat", "Khamroev", "Asatullo ugli", "a.khamroev@atg.uz", "94 888 05 52", "7520", "HO-HR",
            "Старший специалист по обучению и развитию персонала", "Senior Specialist on Personnel Training and Development of Human Resources", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-136", "Жоюй", "Сюй", null, "Ruoyu", "Xu", null, "xuruoyu@atg.uz", "50 050 75 52", "7703", "HO-HR",
            "Ведущий специалист по подбору персонала", "Recruiting Leading Specialist of Human Resources Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-137", "Сардор", "Мирзахмедов", "Баходирович", "Sardor", "Mirzakhmedov", "Bakhodirovich", "s.mirzakhmedov@atg.uz", "93 111 26 67", "7517", "HO-HR",
            "Главный специалист по подбору персонала", "Recruiting Chief Specialist of Human Resources Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-138", "Алишер", "Абдурахимов", null, "Alisher", "Abdurakhimov", null, "a.abdurakhimov@atg.uz", "94 660 22 86", "7880", "HO-HR",
            "Главный специалист по компенсациям и льготам", "Chief specialist on Compensation and Benefits of Human Resources Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-139", "Тяньюй", "Бай", null, "Tianyu", "Bai", null, "baitianyu@atg.uz", "93 111 63 80", null, "HO-HR",
            "Специалист по обучению и развитию персонала", "Specialist on Personnel Training and Development of Human Resources Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-140", "Хадичабону", "Каримбердиева", null, "Khadichabonu", "Karimberdieva", null, "kh.karimberdieva@atg.uz", "94 660 69 25", "7559", "HO-HR",
            "Специалист по социальным вопросам и корпоративной культуре", "Specialist on Social Issues and Corporate Culture of Human Resources Department", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-141", "Бинь", "Ван", null, "Bin", "Wang", null, "wangbin@atg.uz", "50 122 79 48", null, "HO-HR",
            "Специалист по обучению и развитию персонала", "Specialist on Personnel Training and Development of Human Resources Department", "SPECIALIST", UserRole.HOEngineer),

        // Administrative and Utility Issues Department
        new("ATG-142", "Хуршид", "Закиров", "Эргашевич", "Khurshid", "Zakirov", "Ergashevich", "khur.zakirov@atg.uz", "93 111 31 15", "7778", "HO-ADM",
            "Начальник департамента по административно-хозяйственным вопросам", "Manager of Administrative and Utility Issues Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-143", "Цзылун", "Ван", null, "Zilong", "Wang", null, "wangzilong@atg.uz", "97 701 12 46", "7676", "HO-ADM",
            "Заместитель начальника департамента по административно-хозяйственным вопросам", "Deputy Manager of Administrative and Utility Issues Department", "MANAGER", UserRole.HONachalnik),
        new("ATG-144", "Сардор", "Саидгазиев", "Темурович", "Sardor", "Saidgaziev", "Temurovich", "s.saidgaziev@atg.uz", "97 444 09 08", "7979", "HO-ADM-ADMIN",
            "Начальник административного отдела", "Manager of Administrative Section of Administrative and Utility Issues Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-145", "Абубакир", "Мусабаев", "Ниязбекович", "Abubakir", "Musabaev", "Niyazbekovich", "a.musabaev@atg.uz", "50 122 06 38", "7635", "HO-ADM-ADMIN",
            "Кладовщик (главный специалист) административного отдела", "Stock keeper (Chief specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-146", "Жасур", "Исраилов", "Тулкунович", "Jasur", "Israilov", "Tulkunovich", "j.israilov@atg.uz", "94 660 21 31", "7766", "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (главный специалист) административного отдела", "Organizational Issues Officer (Chief specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-147", "Жахонгир", "Шарипов", "Тураевич", "Jakhongir", "Sharipov", "Turaevich", "j.sharipov@atg.uz", "50 122 06 37", "7744", "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (главный специалист) административного отдела", "Organizational Issues Officer (Chief specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-148", "Шерзод", "Умаров", "Абдурахимович", "Sherzod", "Umarov", "Abdurakhimovich", "sh.umarov@atg.uz", "94 660 23 93", "7775", "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (главный специалист) административного отдела", "Organizational Issues Officer (Chief specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-149", "Санжар", "Ганиходжаев", "Расулович", "Sanjar", "Ganikhodjaev", "Rasulovich", "s.ganikhodjaev@atg.uz", "97 701 82 00", "7533", "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (главный специалист) административного отдела", "Organizational Issues Officer (Chief specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-150", "Цзышунь", "Гун", null, "Zishun", "Gong", null, "gongzishun@atg.uz", "94 655 86 26", null, "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (ведущий специалист) административного отдела", "Organizational Issues Officer (Leading specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-151", "Цзиньлун", "Хоу", null, "Jinlong", "Hou", null, "houjinlong@atg.uz", "94 660 37 85", null, "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (опытный специалист) административного отдела", "Organizational Issues Officer (Experienced specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-152", "Шуай", "Цзинь", null, "Shuai", "Jin", null, "jinshuai@atg.uz", "93 505 52 29", null, "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (опытный специалист) административного отдела", "Organizational Issues Officer (Experienced specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-153", "Цзюньфэн", "Чэн", null, "Junfeng", "Cheng", null, "chengjunfeng@atg.uz", "94 888 16 30", null, "HO-ADM-ADMIN",
            "Специалист по организационным вопросам (старший специалист) административного отдела", "Organizational Issues Officer (Senior specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-154", "Дилмурод", "Жалилов", "Халилович", "Dilmurod", "Jalilov", "Khalilovich", "d.jalilov@atg.uz", "94 660 22 71", "7711", "HO-ADM-ADMIN",
            "Координатор по хозяйственным вопросам (опытный специалист) административного отдела", "Household coordinator (Experienced specialist) of Administrative Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-155", "Шухратали", "Умаралиев", "Сайдинабиевич", "Shukhratali", "Umaraliev", "Saydinabievich", "sh.umaraliev@atg.uz", "94 660 80 88", "7733", "HO-ADM-TRANS",
            "Начальник транспортного отдела", "Manager of Transport Section of Administrative and Utility Issues Department", "NACHALNIK", UserRole.HONachalnik),
        new("ATG-156", "Хайрулла", "Пулатов", "Омонуллаевич", "Hayrulla", "Pulatov", "Omonullaevich", "kh.pulatov@atg.uz", "94 660 00 11", "7755", "HO-ADM-TRANS",
            "Диспетчер движения (ведущий специалист) транспортного отдела", "Traffic Controller (Leading specialist) of Transport Section", "SPECIALIST", UserRole.HOEngineer),
        new("ATG-157", "Камалитдин", "Атаходжаев", "Сайфутдинович", "Kamalitdin", "Atakhodjaev", "Sayfutdinovich", "k.atakhodjaev@atg.uz", "94 777 06 33", "7779", "HO-ADM-TRANS",
            "Механик-инженер (ведущий специалист) транспортного отдела", "Mechanic engineer (Leading specialist) of Transport Section", "SPECIALIST", UserRole.HOEngineer),
    ];
}
