// <auto-generated />
using System;
using ATG.Platform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ATG.Platform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701083502_AddHrLeavePdfPresentation")]
    partial class AddHrLeavePdfPresentation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ATG.Platform.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("IncomingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IncomingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RecordBook")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SenderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TitleRu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TranslationRequestCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.DocumentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("DocumentId");

                    b.ToTable("document_activities", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("hr_leave_approvers", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveRequestDetail", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EimzoCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("HrDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("HrReviewCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("HrTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfPresentationStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PdfSignedStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PdfStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SigningPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("DocumentId");

                    b.HasIndex("HrDepartmentId");

                    b.ToTable("hr_leave_request_details", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DaysCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoteEn")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NoteRu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("hr_leave_request_items", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CertificateSerial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Pkcs7Base64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SignerCn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SignerPinpp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SignerTin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SignerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SignerUserId");

                    b.ToTable("hr_leave_signatures", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.IncomingLetterComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DocumentId");

                    b.ToTable("incoming_letter_comments", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.IncomingLetterDetail", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("InformedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("RoutedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("RoutedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoutedToDepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId");

                    b.HasIndex("RoutedById");

                    b.HasIndex("RoutedToDepartmentId");

                    b.ToTable("incoming_letter_details", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.IncomingLetterRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Informed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("InformedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("incoming_letter_recipients", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffiliationNote")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentKey")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("DeliveryIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAffiliated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MarketingRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("MeetsTzRequirements")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OfferAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateOnly?>("OfferDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OfferValidityDate")
                        .HasColumnType("date");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("VatIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("WarrantyTerms")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarketingRecordId");

                    b.ToTable("marketing_offers", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingPortalApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BudgetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MarketingRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProcurementPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketingRecordId");

                    b.HasIndex("ProcurementPlanId");

                    b.ToTable("marketing_portal_approvals", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingProcurementPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AttachmentKey")
                        .HasColumnType("text");

                    b.Property<string>("CompetitionCriteria")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EvaluationGroupMembers")
                        .HasColumnType("text");

                    b.Property<string>("Incoterms")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("MarketingRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("NdsNote")
                        .HasColumnType("text");

                    b.Property<string>("ProcurementMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RejectionNotes")
                        .HasColumnType("text");

                    b.Property<decimal?>("StartPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("StartPriceCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("VatConsidered")
                        .HasColumnType("boolean");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarketingRecordId");

                    b.ToTable("marketing_procurement_plans", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AssignedByManagerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BudgetAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("BudgetCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DeadlineBaseDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeadlineDate")
                        .HasColumnType("date");

                    b.Property<int?>("DeadlineWorkingDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("HandoverDate")
                        .HasColumnType("date");

                    b.Property<string>("InitiatorDepartment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("InitiatorFullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LegalBasis")
                        .HasColumnType("text");

                    b.Property<Guid?>("MarketingExecutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlanApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PlanPreparedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PlanRegisteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PlanSentToManagementAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PlanSubmittedToPortalAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PortalApprovalStartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PortalApprovalType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PortalBudgetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PortalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProcurementMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RegisteredDate")
                        .HasColumnType("date");

                    b.Property<int?>("RequestCategory")
                        .HasColumnType("integer");

                    b.Property<string>("RequestTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RfqDocumentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RfqDocumentStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("RfqOpenSearchDone")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RfqPreparedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("RfqPublishedAtgSite")
                        .HasColumnType("boolean");

                    b.Property<bool>("RfqPublishedTenderweek")
                        .HasColumnType("boolean");

                    b.Property<bool>("RfqSentToDistributor")
                        .HasColumnType("boolean");

                    b.Property<bool>("RfqSentToVendor")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StrategyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StrategyNumberManual")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TzIssueDescription")
                        .HasColumnType("text");

                    b.Property<bool>("TzIssueFound")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TzIssueResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByManagerId");

                    b.HasIndex("DeadlineDate");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("MarketingExecutorId");

                    b.HasIndex("PortalNumber")
                        .IsUnique();

                    b.HasIndex("RequestCategory");

                    b.HasIndex("Status");

                    b.ToTable("marketing_records", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingRfqChannelRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("HelpDeskTicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarketingRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("WorkTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("HelpDeskTicketId");

                    b.HasIndex("MarketingRecordId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("marketing_rfq_channel_requests", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrgType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementMarketingPlanApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("procurement_marketing_plan_approvers", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementRequestApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("procurement_request_approvers", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UploadedById");

                    b.ToTable("procurement_request_attachments", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementRequestDetail", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ContractsAcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ContractsAssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ContractsSpecialistId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractsSubPhase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("ContractsTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EamFormationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EamNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("InitiatorDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MarketingAcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MarketingActiveBranch")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("MarketingAssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MarketingBranchStartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MarketingCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MarketingCurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("MarketingPlanApprovalSubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MarketingPlanRegisteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("MarketingPlanRegisteredById")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketingPlanRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("MarketingSpecialistId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketingSubPhase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("MarketingTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RegionLabelEn")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RegionLabelRu")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ResponsibleTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId");

                    b.HasIndex("ContractsSpecialistId");

                    b.HasIndex("InitiatorDepartmentId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("MarketingSpecialistId");

                    b.ToTable("procurement_request_details", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementStepComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DocumentId", "Phase", "StepNumber");

                    b.ToTable("procurement_step_comments", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.RfqDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DispatchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("FollowupPhoneCalled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FollowupSentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MarketingRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecipientPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ResponseReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketingRecordId");

                    b.ToTable("rfq_dispatches", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TargetDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TargetDepartmentId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.TicketActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("TicketId");

                    b.ToTable("ticket_activities", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstNameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitleEn")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("JobTitleRu")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastNameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MiddleNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pinpp")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PositionId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("work_tasks", (string)null);
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Department", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Document", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Author");

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.DocumentActivity", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Document", "Document")
                        .WithMany("Activities")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveApprover", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.HrLeaveRequestDetail", "Request")
                        .WithMany("Approvers")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveRequestDetail", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.Document", "Document")
                        .WithOne()
                        .HasForeignKey("ATG.Platform.Domain.Entities.HrLeaveRequestDetail", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Department", "HrDepartment")
                        .WithMany()
                        .HasForeignKey("HrDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("HrDepartment");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveRequestItem", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.HrLeaveRequestDetail", "Request")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveSignature", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.HrLeaveRequestDetail", "Request")
                        .WithMany("Signatures")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "Signer")
                        .WithMany()
                        .HasForeignKey("SignerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Signer");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.IncomingLetterComment", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.IncomingLetterDetail", "Letter")
                        .WithMany("Comments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Letter");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.IncomingLetterDetail", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.Document", "Document")
                        .WithOne()
                        .HasForeignKey("ATG.Platform.Domain.Entities.IncomingLetterDetail", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "RoutedBy")
                        .WithMany()
                        .HasForeignKey("RoutedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.Department", "RoutedToDepartment")
                        .WithMany()
                        .HasForeignKey("RoutedToDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("RoutedBy");

                    b.Navigation("RoutedToDepartment");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.IncomingLetterRecipient", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.IncomingLetterDetail", "Letter")
                        .WithMany("Recipients")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Letter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingOffer", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.MarketingRecord", "Record")
                        .WithMany("Offers")
                        .HasForeignKey("MarketingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingPortalApproval", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.MarketingRecord", "Record")
                        .WithMany("PortalApprovals")
                        .HasForeignKey("MarketingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.MarketingProcurementPlan", "ProcurementPlan")
                        .WithMany()
                        .HasForeignKey("ProcurementPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProcurementPlan");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingProcurementPlan", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.MarketingRecord", "Record")
                        .WithMany("Plans")
                        .HasForeignKey("MarketingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingRecord", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "AssignedByManager")
                        .WithMany()
                        .HasForeignKey("AssignedByManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.ProcurementRequestDetail", "Request")
                        .WithOne("MarketingRecord")
                        .HasForeignKey("ATG.Platform.Domain.Entities.MarketingRecord", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "MarketingExecutor")
                        .WithMany()
                        .HasForeignKey("MarketingExecutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedByManager");

                    b.Navigation("MarketingExecutor");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingRfqChannelRequest", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.MarketingRecord", "Record")
                        .WithMany("RfqChannelRequests")
                        .HasForeignKey("MarketingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Organization", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.Organization", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementMarketingPlanApprover", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.ProcurementRequestDetail", "Request")
                        .WithMany("MarketingPlanApprovers")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementRequestApprover", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.ProcurementRequestDetail", "Request")
                        .WithMany("Approvers")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementRequestAttachment", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.ProcurementRequestDetail", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementRequestDetail", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "ContractsSpecialist")
                        .WithMany()
                        .HasForeignKey("ContractsSpecialistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.Document", "Document")
                        .WithOne()
                        .HasForeignKey("ATG.Platform.Domain.Entities.ProcurementRequestDetail", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Department", "InitiatorDepartment")
                        .WithMany()
                        .HasForeignKey("InitiatorDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.User", "MarketingSpecialist")
                        .WithMany()
                        .HasForeignKey("MarketingSpecialistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContractsSpecialist");

                    b.Navigation("Document");

                    b.Navigation("Initiator");

                    b.Navigation("InitiatorDepartment");

                    b.Navigation("MarketingSpecialist");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementStepComment", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.ProcurementRequestDetail", "Request")
                        .WithMany("StepComments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.RfqDispatch", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.MarketingRecord", "Record")
                        .WithMany("RfqDispatches")
                        .HasForeignKey("MarketingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ATG.Platform.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Assignee");

                    b.Navigation("Organization");

                    b.Navigation("Requester");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.TicketActivity", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Activities")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.User", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ATG.Platform.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId");

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("ATG.Platform.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATG.Platform.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Document", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.HrLeaveRequestDetail", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Items");

                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.IncomingLetterDetail", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.MarketingRecord", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Plans");

                    b.Navigation("PortalApprovals");

                    b.Navigation("RfqChannelRequests");

                    b.Navigation("RfqDispatches");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Departments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.ProcurementRequestDetail", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Attachments");

                    b.Navigation("MarketingPlanApprovers");

                    b.Navigation("MarketingRecord");

                    b.Navigation("StepComments");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ATG.Platform.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
